import {createContext,useContext,useState,useEffect,useCallback,ReactNode} from "react";
import { setLanguageFromCountry } from "@/lib/language-preferences";
export interface AuthUser{id:number;username:string;displayName:string;avatarUrl:string|null;country:string|null;countryFlag:string|null;age:number|null;bio:string;website:string|null;createdAt:string}
interface AuthContextValue{user:AuthUser|null;token:string|null;login:(token:string,user:AuthUser)=>void;logout:()=>void;updateUser:(user:AuthUser)=>void;refreshUser:()=>Promise<void>;isLoading:boolean}
const AuthContext=createContext<AuthContextValue|null>(null);const TOKEN_KEY="yuniko_token";const USER_KEY="yuniko_user";const USER_ID_KEY="yuniko_user_id";
export function AuthProvider({children}:{children:ReactNode}){const[user,setUser]=useState<AuthUser|null>(null);const[token,setToken]=useState<string|null>(null);const[isLoading,setIsLoading]=useState(true);useEffect(()=>{const t=localStorage.getItem(TOKEN_KEY),u=localStorage.getItem(USER_KEY);if(t&&u){try{const parsed=JSON.parse(u) as AuthUser;setToken(t);setUser(parsed);localStorage.setItem(USER_ID_KEY,String(parsed.id))}catch{localStorage.removeItem(TOKEN_KEY);localStorage.removeItem(USER_KEY);localStorage.removeItem(USER_ID_KEY)}}setIsLoading(false)},[]);
 const login=(t:string,u:AuthUser)=>{setToken(t);setUser(u);localStorage.setItem(TOKEN_KEY,t);localStorage.setItem(USER_KEY,JSON.stringify(u));localStorage.setItem(USER_ID_KEY,String(u.id));if(u.country)setLanguageFromCountry(u.country)};
 const logout=()=>{setToken(null);setUser(null);localStorage.removeItem(TOKEN_KEY);localStorage.removeItem(USER_KEY);localStorage.removeItem(USER_ID_KEY)};
 const updateUser=(u:AuthUser)=>{setUser(u);localStorage.setItem(USER_KEY,JSON.stringify(u));localStorage.setItem(USER_ID_KEY,String(u.id))};
 const refreshUser=useCallback(async()=>{const storedToken=localStorage.getItem(TOKEN_KEY);if(!storedToken)return;try{const res=await fetch("/api/auth/me",{headers:{Authorization:`Bearer ${storedToken}`}});if(res.status===401){logout();return}if(res.ok){const fresh=await res.json() as AuthUser;setUser(fresh);localStorage.setItem(USER_KEY,JSON.stringify(fresh));localStorage.setItem(USER_ID_KEY,String(fresh.id));if(fresh.country)setLanguageFromCountry(fresh.country)}}catch{}},[]);
 return <AuthContext.Provider value={{user,token,login,logout,updateUser,refreshUser,isLoading}}>{children}</AuthContext.Provider>}
export function useAuth(){const ctx=useContext(AuthContext);if(!ctx)throw new Error("useAuth must be used inside AuthProvider");return ctx}
