import { useInfiniteQuery } from "@tanstack/react-query";
import { fetchWorldFeed } from "@/features/feed/feed-api";

export interface WorldFeedAuthor { displayName:string; username:string; avatarUrl:string|null; verified?:boolean; isFollowing?:boolean }
export interface WorldFeedPost { post:any; author:WorldFeedAuthor; raw:any }
export interface WorldFeedPage { items:WorldFeedPost[]; nextCursor:number|null; hasMore:boolean }
function normalizeCursor(value:unknown):number|null{if(typeof value==="number"&&Number.isSafeInteger(value)&&value>0)return value;if(typeof value==="string"&&value.trim()!==""){const n=Number(value);return Number.isSafeInteger(n)&&n>0?n:null}return null}
function relativeTime(iso:string){const diff=Math.max(0,Date.now()-new Date(iso).getTime()),m=Math.floor(diff/60000);if(m<1)return"just now";if(m<60)return`${m}m`;const h=Math.floor(m/60);if(h<24)return`${h}h`;return`${Math.floor(h/24)}d`}
function convert(raw:any):WorldFeedPost{let mediaItems:string[]|undefined;if(raw.mediaItems){try{const parsed=typeof raw.mediaItems==="string"?JSON.parse(raw.mediaItems):raw.mediaItems;if(Array.isArray(parsed))mediaItems=parsed}catch{}}return{raw,post:{id:raw.id,userId:raw.userId,imageUrl:raw.mediaUrl??"",mediaType:raw.mediaType??"text",mediaItems,caption:raw.caption??"",hashtags:raw.hashtags?String(raw.hashtags).split(/[\s,]+/).filter(Boolean):[],likes:raw.likes??0,comments:raw.comments??0,shares:raw.shares??0,saves:raw.saves??0,timestamp:relativeTime(raw.createdAt),isLiked:Boolean(raw.liked),isSaved:Boolean(raw.saved),location:raw.location??undefined,views:raw.views??0,isSponsored:Boolean(raw.isSponsored)},author:{displayName:raw.authorDisplayName??"Yuniko user",username:raw.authorUsername??"user",avatarUrl:raw.authorAvatarUrl??null,verified:Boolean(raw.authorVerified),isFollowing:Boolean(raw.following??raw.isFollowing)}}}
async function fetchWorldFeedPage(cursor:number|null,signal?:AbortSignal):Promise<WorldFeedPage>{const data=await fetchWorldFeed({cursor,limit:20,signal});const posts=Array.isArray(data.posts)?data.posts:[];const nextCursor=normalizeCursor(data.nextCursor);return{items:posts.map(convert),nextCursor,hasMore:Boolean(data.hasMore)&&nextCursor!==null&&posts.length>0}}
export const worldFeedKeys={all:(userId:number|null)=>["world-feed",userId] as const};
export function useWorldFeed(userId:number|null){return useInfiniteQuery({queryKey:worldFeedKeys.all(userId),enabled:userId!==null,initialPageParam:null as number|null,queryFn:({pageParam,signal})=>fetchWorldFeedPage(pageParam,signal),getNextPageParam:last=>last.hasMore&&last.nextCursor!==null?last.nextCursor:undefined,staleTime:30_000,gcTime:15*60_000,retry:1,refetchOnWindowFocus:true,refetchOnMount:true})}
export function flattenWorldFeed(data:{pages?:WorldFeedPage[]}|undefined):WorldFeedPost[]{return data?.pages?.flatMap(page=>page.items)??[]}