import { Router, Request, Response } from "express";
import { db } from "@workspace/db";
import { liveSessionsTable, usersTable } from "@workspace/db/schema";
import { and, desc, eq } from "drizzle-orm";
import { authMiddleware } from "../middlewares/auth";
const router=Router();type R=Request&{userId?:number};type Signal={type:"join"|"offer"|"answer"|"candidate"|"leave"|"end";from:string;to?:string;data?:unknown};type Peer={userId:number;responses:Set<Response>};const livePeers=new Map<number,Map<string,Peer>>();
function send(peer:Peer,message:Signal){for(const res of peer.responses){try{res.write(`event: signal\ndata: ${JSON.stringify(message)}\n\n`)}catch{}}}
function broadcast(sessionId:number,message:Signal,except?:string){const peers=livePeers.get(sessionId);if(!peers)return;for(const[id,peer]of peers)if(id!==except)send(peer,message)}
function ensureSessionPeers(sessionId:number){let peers=livePeers.get(sessionId);if(!peers){peers=new Map();livePeers.set(sessionId,peers)}return peers}
router.post("/live",authMiddleware,async(req:R,res)=>{try{const[session]=await db.insert(liveSessionsTable).values({hostUserId:req.userId!,title:String(req.body?.title??"").trim(),streamUrl:null}).returning();ensureSessionPeers(session.id);return res.status(201).json({live:session})}catch(e){console.error(e);return res.status(500).json({error:"Server error"})}});
router.get("/live",authMiddleware,async(_req:R,res)=>{try{const lives=await db.select({id:liveSessionsTable.id,hostUserId:liveSessionsTable.hostUserId,title:liveSessionsTable.title,streamUrl:liveSessionsTable.streamUrl,status:liveSessionsTable.status,startedAt:liveSessionsTable.startedAt,hostUsername:usersTable.username,hostDisplayName:usersTable.displayName,hostAvatar:usersTable.avatarUrl}).from(liveSessionsTable).innerJoin(usersTable,eq(usersTable.id,liveSessionsTable.hostUserId)).where(and(eq(liveSessionsTable.status,"live"),eq(liveSessionsTable.isPublic,true))).orderBy(desc(liveSessionsTable.startedAt)).limit(100);return res.json({lives})}catch(e){console.error(e);return res.status(500).json({error:"Server error"})}});
router.post("/live/:id/join",authMiddleware,async(req:R,res)=>{const sessionId=Number(req.params.id);const peerId=String(req.body?.peerId??"").trim();if(!Number.isInteger(sessionId)||!peerId)return res.status(400).json({error:"Invalid live or peer"});const[live]=await db.select().from(liveSessionsTable).where(eq(liveSessionsTable.id,sessionId));if(!live||live.status!=="live")return res.status(404).json({error:"Live not found"});const peers=ensureSessionPeers(sessionId);const existing=[...peers.entries()].map(([id,p])=>({id,userId:p.userId}));const peer=peers.get(peerId)??{userId:req.userId!,responses:new Set<Response>()};peer.userId=req.userId!;peers.set(peerId,peer);broadcast(sessionId,{type:"join",from:peerId,data:{userId:req.userId}},peerId);return res.json({joined:true,peers:existing.filter(p=>p.id!==peerId)})});
router.get("/live/:id/signals",authMiddleware,async(req:R,res)=>{const sessionId=Number(req.params.id);const peerId=String(req.query.peerId??"").trim();if(!Number.isInteger(sessionId)||!peerId)return res.status(400).end();const peers=ensureSessionPeers(sessionId);const peer=peers.get(peerId)??{userId:req.userId!,responses:new Set<Response>()};peer.userId=req.userId!;peers.set(peerId,peer);res.setHeader("Content-Type","text/event-stream");res.setHeader("Cache-Control","no-cache");res.setHeader("Connection","keep-alive");res.flushHeaders?.();peer.responses.add(res);res.write(`event: ready\ndata: ${JSON.stringify({peerId})}\n\n`);const keepAlive=setInterval(()=>{try{res.write(": ping\n\n")}catch{}},15000);req.on("close",()=>{clearInterval(keepAlive);peer.responses.delete(res);if(peer.responses.size===0&&peers.has(peerId)){peers.delete(peerId);broadcast(sessionId,{type:"leave",from:peerId},peerId);void (async()=>{try{const[live]=await db.select({id:liveSessionsTable.id,hostUserId:liveSessionsTable.hostUserId}).from(liveSessionsTable).where(eq(liveSessionsTable.id,sessionId));const hostStillConnected=[...peers.values()].some(p=>p.userId===live?.hostUserId);if(live&&!hostStillConnected){await db.delete(liveSessionsTable).where(and(eq(liveSessionsTable.id,sessionId),eq(liveSessionsTable.hostUserId,live.hostUserId)));for(const p of peers.values())for(const response of p.responses){try{response.write(`event: signal\ndata: ${JSON.stringify({type:"end",from:`host:${live.hostUserId}`})}\n\n`)}catch{}}}}catch{}})()}if(peers.size===0)livePeers.delete(sessionId)})});
router.post("/live/:id/signal",authMiddleware,async(req:R,res)=>{const sessionId=Number(req.params.id);const from=String(req.body?.from??"").trim();const to=req.body?.to?String(req.body.to):undefined;const type=req.body?.type as Signal["type"];if(!Number.isInteger(sessionId)||!from||!["offer","answer","candidate","leave"].includes(type))return res.status(400).json({error:"Invalid signal"});const peers=livePeers.get(sessionId);if(!peers)return res.status(404).json({error:"Live not active"});const message:Signal={type,from,to,data:req.body?.data};if(to){const target=peers.get(to);if(target)send(target,message)}else broadcast(sessionId,message,from);return res.json({delivered:true})});
router.patch("/live/:id/end",authMiddleware,async(req:R,res)=>{try{const sessionId=Number(req.params.id);const[live]=await db.delete(liveSessionsTable).where(and(eq(liveSessionsTable.id,sessionId),eq(liveSessionsTable.hostUserId,req.userId!))).returning();if(!live)return res.status(404).json({error:"Live not found"});broadcast(sessionId,{type:"end",from:`host:${req.userId}`});for(const peer of livePeers.get(sessionId)?.values()??[])for(const response of peer.responses){try{response.end()}catch{}}livePeers.delete(sessionId);return res.json({live:{...live,status:"ended",endedAt:new Date()}})}catch(e){console.error(e);return res.status(500).json({error:"Server error"})}});
router.get("/live/:id/stream",authMiddleware,async(req:R,res)=>{res.setHeader("Content-Type","text/event-stream");res.setHeader("Cache-Control","no-cache");res.setHeader("Connection","keep-alive");res.flushHeaders?.();const timer=setInterval(async()=>{try{const[live]=await db.select().from(liveSessionsTable).where(eq(liveSessionsTable.id,Number(req.params.id)));if(!live){res.end();clearInterval(timer);return}res.write(`event: live\ndata: ${JSON.stringify(live)}\n\n`)}catch{}},3000);req.on("close",()=>clearInterval(timer))});
export default router;
