import {Router,type Request} from "express";import {env as cloudflareEnv} from "cloudflare:workers";import {authMiddleware} from "../middlewares/auth";import {eq,insertRow,selectRows,updateRows,deleteRows,supabaseError} from "../lib/supabase";
const router=Router();type R=Request&{userId?:number};
const user=async(id:number)=>{const[r]=await selectRows("users",{filters:[eq("id",id)],limit:1});return r??null};
const friend=async(a:number,b:number)=>{const f=await selectRows("follows",{limit:5000});return f.some(x=>Number(x.followerId)===a&&Number(x.followingId)===b)&&f.some(x=>Number(x.followerId)===b&&Number(x.followingId)===a)};
type CallSignalStub={sendInvite(payload:unknown):Promise<void>;emit(event:string,payload:unknown):Promise<void>;isInboxOnline():Promise<boolean>;startCall():Promise<void>;acceptCall():Promise<boolean>;rejectCall():Promise<boolean>;endCall():Promise<boolean>};type CallSignalNamespace={getByName(name:string):CallSignalStub};const callSignal=()=>{const ns=(cloudflareEnv as unknown as {CALL_SIGNAL?:CallSignalNamespace}).CALL_SIGNAL;if(!ns)throw new Error("CALL_SIGNAL binding is not configured");return ns;};

router.post("/calls/start",authMiddleware,async(req:R,res)=>{
const callerId=Number(req.userId),calleeId=Number(req.body?.calleeId),callType=req.body?.callType==="video"?"video":"voice";
try{const callee=await user(calleeId);if(!callee||!(await friend(callerId,calleeId)))return res.status(403).json({error:"Calls are available between friends"});const caller=await user(callerId),roomId=crypto.randomUUID();const room=callSignal().getByName("room:"+roomId);const inbox=callSignal().getByName("user:"+calleeId);if(!(await inbox.isInboxOnline()))return res.status(409).json({error:"User is offline"});await room.startCall();try{await inbox.sendInvite({type:"incoming-call",roomId,callType,callerId,user:{id:callerId,displayName:String(caller?.displayName??"User"),avatarUrl:caller?.avatarUrl??null}});}catch(e){await room.endCall();throw e;}return res.status(201).json({call:{id:roomId,roomId,callType,status:"ringing",callerId,calleeId}});}catch(e){return res.status(503).json({error:e instanceof Error?e.message:"Call signaling unavailable"});}
});
router.post("/calls/:id/answer",authMiddleware,async(req:R,res)=>{const roomId=String(req.params.id??"").trim(),calleeId=Number(req.userId),callerId=Number(req.body?.callerId);if(!roomId||!Number.isInteger(callerId)||callerId<=0)return res.status(400).json({error:"Invalid call"});try{if(!(await user(callerId))||!(await friend(calleeId,callerId)))return res.status(403).json({error:"Calls are available between friends"});const accepted=await callSignal().getByName("room:"+roomId).acceptCall();if(!accepted)return res.status(410).json({error:"Call has already ended"});return res.json({answered:true});}catch(e){return res.status(503).json({error:e instanceof Error?e.message:"Call signaling unavailable"});}});
router.post("/calls/:id/reject",authMiddleware,async(req:R,res)=>{const roomId=String(req.params.id??"").trim(),calleeId=Number(req.userId),callerId=Number(req.body?.callerId);if(!roomId||!Number.isInteger(callerId)||callerId<=0)return res.status(400).json({error:"Invalid call"});try{if(!(await user(callerId))||!(await friend(calleeId,callerId)))return res.status(403).json({error:"Calls are available between friends"});const rejected=await callSignal().getByName("room:"+roomId).rejectCall();if(!rejected)return res.status(410).json({error:"Call has already ended"});return res.json({rejected:true});}catch(e){return res.status(503).json({error:e instanceof Error?e.message:"Call signaling unavailable"});}});
router.post("/calls/:id/end",authMiddleware,async(req:R,res)=>{const roomId=String(req.params.id??"").trim(),userId=Number(req.userId);if(!roomId)return res.status(400).json({error:"Invalid call"});try{await callSignal().getByName("room:"+roomId).endCall();return res.json({ended:true});}catch(e){return res.status(503).json({error:e instanceof Error?e.message:"Call signaling unavailable"});}});
router.get("/calls/history",authMiddleware,async(_req:R,res)=>res.json({calls:[]}));
router.post("/messages/devices",authMiddleware,async(req:R,res)=>{try{const u=Number(req.userId),d=String(req.body?.deviceId??""),k=String(req.body?.publicKey??"");if(!d||!k)return res.status(400).json({error:"Missing device key"});const rows=await selectRows("message_devices",{filters:[eq("userId",u),eq("deviceId",d)],limit:1});if(rows.length)await updateRows("message_devices",{publicKey:k,lastSeenAt:new Date(),revokedAt:null},[eq("userId",u),eq("deviceId",d)]);else await insertRow("message_devices",{userId:u,deviceId:d,publicKey:k,label:null,createdAt:new Date(),lastSeenAt:new Date(),revokedAt:null});return res.json({registered:true})}catch(e){return supabaseError(res,e)}});
router.get("/messages/users/:userId/key",authMiddleware,async(req:R,res)=>{try{const rows=await selectRows("message_devices",{filters:[eq("userId",Number(req.params.userId))],limit:20}),r=rows.find(x=>!x.revokedAt);return res.json({publicKey:r?.publicKey??null})}catch(e){return supabaseError(res,e)}});
export default router;