import {Router,type Request} from "express";import {env as cloudflareEnv} from "cloudflare:workers";import {authMiddleware} from "../middlewares/auth";import {eq,insertRow,selectRows,updateRows,deleteRows,supabaseError} from "../lib/supabase";
const router=Router();type R=Request&{userId?:number};
const user=async(id:number)=>{const[r]=await selectRows("users",{filters:[eq("id",id)],limit:1});return r??null};
const member=async(c:number,u:number)=>{const[r]=await selectRows("conversation_members",{filters:[eq("conversationId",c),eq("userId",u)],limit:1});return r??null};
const friend=async(a:number,b:number)=>{const f=await selectRows("follows",{limit:5000});return f.some(x=>Number(x.followerId)===a&&Number(x.followingId)===b)&&f.some(x=>Number(x.followerId)===b&&Number(x.followingId)===a)};
type CallSignalStub={sendInvite(payload:unknown):Promise<void>;emit(event:string,payload:unknown):Promise<void>;isInboxOnline():Promise<boolean>;startCall():Promise<void>;acceptCall():Promise<boolean>;rejectCall():Promise<boolean>;endCall():Promise<boolean>};type CallSignalNamespace={getByName(name:string):CallSignalStub};const callSignal=()=>{const ns=(cloudflareEnv as unknown as {CALL_SIGNAL?:CallSignalNamespace}).CALL_SIGNAL;if(!ns)throw new Error("CALL_SIGNAL binding is not configured");return ns;};

router.get("/groups",authMiddleware,async(req:R,res)=>{try{const ms=await selectRows("group_members",{filters:[eq("userId",Number(req.userId))],limit:500}),ids=ms.map(x=>Number(x.conversationId)),gs=await selectRows("conversation_groups",{limit:500}),gm=await selectRows("group_members",{limit:5000});return res.json({groups:gs.filter(g=>ids.includes(Number(g.conversationId))).map(g=>({id:Number(g.conversationId),name:String(g.name),description:String(g.description??""),avatarUrl:g.avatarUrl??null,ownerId:Number(g.ownerId),memberCount:gm.filter(m=>Number(m.conversationId)===Number(g.conversationId)).length}))});}catch(e){return supabaseError(res,e)}});
router.post("/groups",authMiddleware,async(req:R,res)=>{const ownerId=Number(req.userId),name=String(req.body?.name??"").trim();if(!name||name.length>80)return res.status(400).json({error:"Invalid group name"});try{const c=await insertRow("conversations",{createdAt:new Date(),updatedAt:new Date()}),id=Number(c.id);await insertRow("conversation_groups",{conversationId:id,name,description:String(req.body?.description??"").slice(0,500),avatarUrl:null,ownerId,createdAt:new Date(),updatedAt:new Date()});await insertRow("group_members",{conversationId:id,userId:ownerId,role:"owner",joinedAt:new Date(),leftAt:null});await insertRow("conversation_members",{conversationId:id,userId:ownerId,lastReadAt:new Date(),lastActiveAt:new Date(),typingAt:null,muted:false});return res.status(201).json({group:{id,name,ownerId,memberCount:1}})}catch(e){return supabaseError(res,e)}});
router.post("/groups/:id/members",authMiddleware,async(req:R,res)=>{const c=Number(req.params.id),actor=Number(req.userId),u=Number(req.body?.userId);try{const[g]=await selectRows("conversation_groups",{filters:[eq("conversationId",c)],limit:1});if(!g||Number(g.ownerId)!==actor)return res.status(403).json({error:"Only the owner can add members"});if(!(await user(u)))return res.status(404).json({error:"User not found"});if(await member(c,u))return res.json({added:true});await insertRow("group_members",{conversationId:c,userId:u,role:"member",joinedAt:new Date(),leftAt:null});await insertRow("conversation_members",{conversationId:c,userId:u,lastReadAt:new Date(),lastActiveAt:new Date(),typingAt:null,muted:false});return res.json({added:true})}catch(e){return supabaseError(res,e)}});
router.get("/groups/:id",authMiddleware,async(req:R,res)=>{const c=Number(req.params.id),u=Number(req.userId);try{if(!(await member(c,u)))return res.status(403).json({error:"Not a group member"});const[g]=await selectRows("conversation_groups",{filters:[eq("conversationId",c)],limit:1}),ms=await selectRows("group_members",{filters:[eq("conversationId",c)],limit:200}),us=await selectRows("users",{limit:1000}),by=new Map(us.map(x=>[Number(x.id),x]));if(!g)return res.status(404).json({error:"Group not found"});return res.json({group:{id:c,name:String(g.name),description:String(g.description??""),ownerId:Number(g.ownerId),members:ms.map(m=>({id:Number(m.userId),role:String(m.role),displayName:by.get(Number(m.userId))?.displayName??"User",username:by.get(Number(m.userId))?.username??"",avatarUrl:by.get(Number(m.userId))?.avatarUrl??null}))}})}catch(e){return supabaseError(res,e)}});
router.get("/groups/:id/messages",authMiddleware,async(req:R,res)=>{const c=Number(req.params.id),u=Number(req.userId),after=Number(req.query.after??0);try{if(!(await member(c,u)))return res.status(403).json({error:"Not a group member"});const rows=await selectRows("messages",{filters:[eq("conversationId",c)],order:{column:"createdAt",ascending:true},limit:500}),us=await selectRows("users",{limit:1000}),by=new Map(us.map(x=>[Number(x.id),x]));return res.json({messages:rows.filter(x=>Number(x.id)>after).map(x=>({id:Number(x.id),senderId:Number(x.senderId),senderName:by.get(Number(x.senderId))?.displayName??"User",text:String(x.body??""),timestamp:x.createdAt,deleted:Boolean(x.deletedAt),edited:Boolean(x.editedAt)}))})}catch(e){return supabaseError(res,e)}});
router.post("/groups/:id/messages",authMiddleware,async(req:R,res)=>{const c=Number(req.params.id),u=Number(req.userId),text=String(req.body?.text??"").trim();if(!text||text.length>4000)return res.status(400).json({error:"Invalid message"});try{if(!(await member(c,u)))return res.status(403).json({error:"Not a group member"});const now=new Date(),m=await insertRow("messages",{conversationId:c,senderId:u,kind:"text",body:text,mediaUrl:null,durationMs:null,deliveredAt:now,readAt:null,replyToMessageId:null,forwardedFromMessageId:null,editedAt:null,deletedAt:null,createdAt:now});await updateRows("conversations",{updatedAt:now},[eq("id",c)]);return res.status(201).json({message:{id:Number(m.id),senderId:u,text,timestamp:now}})}catch(e){return supabaseError(res,e)}});
router.post("/calls/start",authMiddleware,async(req:R,res)=>{
const callerId=Number(req.userId),calleeId=Number(req.body?.calleeId),callType=req.body?.callType==="video"?"video":"voice";
try{const callee=await user(calleeId);if(!callee||!(await friend(callerId,calleeId)))return res.status(403).json({error:"Calls are available between friends"});const caller=await user(callerId),roomId=crypto.randomUUID();const room=callSignal().getByName("room:"+roomId);const inbox=callSignal().getByName("user:"+calleeId);if(!(await inbox.isInboxOnline()))return res.status(409).json({error:"User is offline"});await room.startCall();try{await inbox.sendInvite({type:"incoming-call",roomId,callType,callerId,user:{id:callerId,displayName:String(caller?.displayName??"User"),avatarUrl:caller?.avatarUrl??null}});}catch(e){await room.endCall();throw e;}return res.status(201).json({call:{id:roomId,roomId,callType,status:"ringing",callerId,calleeId}});}catch(e){return res.status(503).json({error:e instanceof Error?e.message:"Call signaling unavailable"});}
});
router.post("/calls/:id/answer",authMiddleware,async(req:R,res)=>{const roomId=String(req.params.id??"").trim(),calleeId=Number(req.userId),callerId=Number(req.body?.callerId);if(!roomId||!Number.isInteger(callerId)||callerId<=0)return res.status(400).json({error:"Invalid call"});try{if(!(await user(callerId))||!(await friend(calleeId,callerId)))return res.status(403).json({error:"Calls are available between friends"});const accepted=await callSignal().getByName("room:"+roomId).acceptCall();if(!accepted)return res.status(410).json({error:"Call has already ended"});return res.json({answered:true});}catch(e){return res.status(503).json({error:e instanceof Error?e.message:"Call signaling unavailable"});}});
router.post("/calls/:id/reject",authMiddleware,async(req:R,res)=>{const roomId=String(req.params.id??"").trim(),calleeId=Number(req.userId),callerId=Number(req.body?.callerId);if(!roomId||!Number.isInteger(callerId)||callerId<=0)return res.status(400).json({error:"Invalid call"});try{if(!(await user(callerId))||!(await friend(calleeId,callerId)))return res.status(403).json({error:"Calls are available between friends"});const rejected=await callSignal().getByName("room:"+roomId).rejectCall();if(!rejected)return res.status(410).json({error:"Call has already ended"});return res.json({rejected:true});}catch(e){return res.status(503).json({error:e instanceof Error?e.message:"Call signaling unavailable"});}});
router.post("/calls/:id/end",authMiddleware,async(req:R,res)=>{const roomId=String(req.params.id??"").trim(),userId=Number(req.userId);if(!roomId)return res.status(400).json({error:"Invalid call"});try{await callSignal().getByName("room:"+roomId).endCall();return res.json({ended:true});}catch(e){return res.status(503).json({error:e instanceof Error?e.message:"Call signaling unavailable"});}});
router.get("/calls/history",authMiddleware,async(_req:R,res)=>res.json({calls:[]}));
router.post("/messages/devices",authMiddleware,async(req:R,res)=>{try{const u=Number(req.userId),d=String(req.body?.deviceId??""),k=String(req.body?.publicKey??"");if(!d||!k)return res.status(400).json({error:"Missing device key"});const rows=await selectRows("message_devices",{filters:[eq("userId",u),eq("deviceId",d)],limit:1});if(rows.length)await updateRows("message_devices",{publicKey:k,lastSeenAt:new Date(),revokedAt:null},[eq("userId",u),eq("deviceId",d)]);else await insertRow("message_devices",{userId:u,deviceId:d,publicKey:k,label:null,createdAt:new Date(),lastSeenAt:new Date(),revokedAt:null});return res.json({registered:true})}catch(e){return supabaseError(res,e)}});
router.get("/messages/users/:userId/key",authMiddleware,async(req:R,res)=>{try{const rows=await selectRows("message_devices",{filters:[eq("userId",Number(req.params.userId))],limit:20}),r=rows.find(x=>!x.revokedAt);return res.json({publicKey:r?.publicKey??null})}catch(e){return supabaseError(res,e)}});
export default router;