import { Router, Request } from "express";
import { db } from "@workspace/db";
import { usersTable, followsTable, notificationsTable, conversationsTable, conversationMembersTable, messagesTable, messageRequestsTable, blockedUsersTable, archivedConversationsTable } from "@workspace/db/schema";
import { and, desc, eq, ne, or, ilike, sql } from "drizzle-orm";
import { authMiddleware } from "../middlewares/auth";

const socialRouter = Router();
type AuthedRequest = Request & { userId?: number };
const publicUser = { id: usersTable.id, username: usersTable.username, displayName: usersTable.displayName, country: usersTable.country, countryFlag: usersTable.countryFlag, age: usersTable.age, avatarUrl: usersTable.avatarUrl, bio: usersTable.bio, website: usersTable.website, verificationStatus: usersTable.verificationStatus, createdAt: usersTable.createdAt };
const dbError=(res:any,e:unknown)=>{console.error(e);return res.status(500).json({error:"Server error"})};

socialRouter.get("/users/search",authMiddleware,async(req:AuthedRequest,res)=>{const q=String(req.query.q??"").trim();if(q.length<2)return res.json({users:[]});try{const users=await db.select(publicUser).from(usersTable).where(and(ne(usersTable.id,req.userId!),or(ilike(usersTable.username,`%${q}%`),ilike(usersTable.displayName,`%${q}%`)))).limit(25);return res.json({users})}catch(e){return dbError(res,e)}});
socialRouter.get("/users/:id",authMiddleware,async(req:AuthedRequest,res)=>{const id=Number(req.params.id);try{const [user]=await db.select(publicUser).from(usersTable).where(eq(usersTable.id,id)).limit(1);if(!user)return res.status(404).json({error:"User not found"});return res.json({user})}catch(e){return dbError(res,e)}});
socialRouter.post("/users/:id/follow",authMiddleware,async(req:AuthedRequest,res)=>{const id=Number(req.params.id);if(!Number.isInteger(id)||id===req.userId)return res.status(400).json({error:"Invalid user id"});try{await db.insert(followsTable).values({followerId:req.userId!,followingId:id}).onConflictDoNothing();await db.insert(notificationsTable).values({userId:id,actorId:req.userId!,type:"follow",message:"You have a new follower."}).catch(()=>{});return res.json({following:true})}catch(e){return dbError(res,e)}});
socialRouter.delete("/users/:id/follow",authMiddleware,async(req:AuthedRequest,res)=>{try{await db.delete(followsTable).where(and(eq(followsTable.followerId,req.userId!),eq(followsTable.followingId,Number(req.params.id))));return res.json({following:false})}catch(e){return dbError(res,e)}});

socialRouter.get("/notifications",authMiddleware,async(req:AuthedRequest,res)=>{try{const notifications=await db.select().from(notificationsTable).where(eq(notificationsTable.userId,req.userId!)).orderBy(desc(notificationsTable.createdAt)).limit(100);return res.json({notifications})}catch(e){return dbError(res,e)}});
socialRouter.patch("/notifications/:id/read",authMiddleware,async(req:AuthedRequest,res)=>{try{await db.update(notificationsTable).set({readAt:new Date()}).where(and(eq(notificationsTable.id,Number(req.params.id)),eq(notificationsTable.userId,req.userId!)));return res.json({read:true})}catch(e){return dbError(res,e)}});

socialRouter.post("/message-requests",authMiddleware,async(req:AuthedRequest,res)=>{const recipientId=Number(req.body?.recipientId);const message=String(req.body?.message??"").trim();if(!Number.isInteger(recipientId)||recipientId===req.userId)return res.status(400).json({error:"Invalid recipient"});try{const [blocked]=await db.select().from(blockedUsersTable).where(or(and(eq(blockedUsersTable.blockerId,recipientId),eq(blockedUsersTable.blockedId,req.userId!)),and(eq(blockedUsersTable.blockerId,req.userId!),eq(blockedUsersTable.blockedId,recipientId)))).limit(1);if(blocked)return res.status(403).json({error:"Messaging is blocked"});const [row]=await db.insert(messageRequestsTable).values({senderId:req.userId!,recipientId,message,status:"pending"}).onConflictDoUpdate({target:[messageRequestsTable.senderId,messageRequestsTable.recipientId],set:{message,status:"pending",updatedAt:new Date()}}).returning();await db.insert(notificationsTable).values({userId:recipientId,actorId:req.userId!,type:"message_request",message:"You received a message request."});return res.status(201).json({request:row})}catch(e){return dbError(res,e)}});
socialRouter.get("/message-requests",authMiddleware,async(req:AuthedRequest,res)=>{try{const rows=await db.select().from(messageRequestsTable).where(or(eq(messageRequestsTable.recipientId,req.userId!),eq(messageRequestsTable.senderId,req.userId!))).orderBy(desc(messageRequestsTable.createdAt));return res.json({requests:rows})}catch(e){return dbError(res,e)}});
socialRouter.patch("/message-requests/:id",authMiddleware,async(req:AuthedRequest,res)=>{const status=["accepted","declined","pending"].includes(req.body?.status)?req.body.status:null;if(!status)return res.status(400).json({error:"Invalid status"});try{const [row]=await db.update(messageRequestsTable).set({status,updatedAt:new Date()}).where(and(eq(messageRequestsTable.id,Number(req.params.id)),eq(messageRequestsTable.recipientId,req.userId!))).returning();if(!row)return res.status(404).json({error:"Request not found"});return res.json({request:row})}catch(e){return dbError(res,e)}});

socialRouter.post("/users/:id/block",authMiddleware,async(req:AuthedRequest,res)=>{const id=Number(req.params.id);if(!Number.isInteger(id)||id===req.userId)return res.status(400).json({error:"Invalid user id"});try{await db.insert(blockedUsersTable).values({blockerId:req.userId!,blockedId:id}).onConflictDoNothing();await db.delete(followsTable).where(or(and(eq(followsTable.followerId,req.userId!),eq(followsTable.followingId,id)),and(eq(followsTable.followerId,id),eq(followsTable.followingId,req.userId!))));return res.json({blocked:true})}catch(e){return dbError(res,e)}});
socialRouter.delete("/users/:id/block",authMiddleware,async(req:AuthedRequest,res)=>{try{await db.delete(blockedUsersTable).where(and(eq(blockedUsersTable.blockerId,req.userId!),eq(blockedUsersTable.blockedId,Number(req.params.id))));return res.json({blocked:false})}catch(e){return dbError(res,e)}});
socialRouter.get("/blocked-users",authMiddleware,async(req:AuthedRequest,res)=>{try{const users=await db.select(publicUser).from(blockedUsersTable).innerJoin(usersTable,eq(usersTable.id,blockedUsersTable.blockedId)).where(eq(blockedUsersTable.blockerId,req.userId!));return res.json({users})}catch(e){return dbError(res,e)}});

socialRouter.post("/conversations/:id/archive",authMiddleware,async(req:AuthedRequest,res)=>{try{await db.insert(archivedConversationsTable).values({conversationId:Number(req.params.id),userId:req.userId!}).onConflictDoNothing();return res.json({archived:true})}catch(e){return dbError(res,e)}});
socialRouter.delete("/conversations/:id/archive",authMiddleware,async(req:AuthedRequest,res)=>{try{await db.delete(archivedConversationsTable).where(and(eq(archivedConversationsTable.conversationId,Number(req.params.id)),eq(archivedConversationsTable.userId,req.userId!)));return res.json({archived:false})}catch(e){return dbError(res,e)}});
socialRouter.get("/conversations/archived",authMiddleware,async(req:AuthedRequest,res)=>{try{const rows=await db.select().from(archivedConversationsTable).where(eq(archivedConversationsTable.userId,req.userId!)).orderBy(desc(archivedConversationsTable.archivedAt));return res.json({conversations:rows})}catch(e){return dbError(res,e)}});

socialRouter.post("/account/verify",authMiddleware,async(req:AuthedRequest,res)=>{try{const [user]=await db.update(usersTable).set({verificationStatus:"pending",verificationRequestedAt:new Date()}).where(eq(usersTable.id,req.userId!)).returning({verificationStatus:usersTable.verificationStatus,verificationRequestedAt:usersTable.verificationRequestedAt});return res.json({verification:user})}catch(e){return dbError(res,e)}});

export default socialRouter;
