import { Router, Request } from "express";
import { db } from "@workspace/db";
import { usersTable,followsTable,notificationsTable,conversationsTable,conversationMembersTable,messagesTable,messageRequestsTable,blockedUsersTable,archivedConversationsTable } from "@workspace/db/schema";
import { and,desc,eq,ne,or,ilike,gt } from "drizzle-orm";
import { authMiddleware } from "../middlewares/auth";
const socialRouter=Router();type AuthedRequest=Request&{userId?:number};
const publicUser={id:usersTable.id,username:usersTable.username,displayName:usersTable.displayName,country:usersTable.country,countryFlag:usersTable.countryFlag,age:usersTable.age,avatarUrl:usersTable.avatarUrl,bio:usersTable.bio,website:usersTable.website,verificationStatus:usersTable.verificationStatus,createdAt:usersTable.createdAt};
const fail=(res:any,e:unknown)=>{console.error(e);return res.status(500).json({error:"Server error"})};

socialRouter.get("/users/search",authMiddleware,async(req:AuthedRequest,res)=>{const q=String(req.query.q??"").trim();if(q.length<2)return res.json({users:[]});try{return res.json({users:await db.select(publicUser).from(usersTable).where(and(ne(usersTable.id,req.userId!),or(ilike(usersTable.username,`%${q}%`),ilike(usersTable.displayName,`%${q}%`)))).limit(25)})}catch(e){return fail(res,e)}});
socialRouter.get("/users/:id",authMiddleware,async(req,res)=>{try{const [user]=await db.select(publicUser).from(usersTable).where(eq(usersTable.id,Number(req.params.id))).limit(1);return user?res.json({user}):res.status(404).json({error:"User not found"})}catch(e){return fail(res,e)}});
socialRouter.post("/users/:id/follow",authMiddleware,async(req:AuthedRequest,res)=>{try{const id=Number(req.params.id);await db.insert(followsTable).values({followerId:req.userId!,followingId:id}).onConflictDoNothing();await db.insert(notificationsTable).values({userId:id,actorId:req.userId!,type:"follow",message:"You have a new follower."}).catch(()=>{});return res.json({following:true})}catch(e){return fail(res,e)}});
socialRouter.delete("/users/:id/follow",authMiddleware,async(req:AuthedRequest,res)=>{try{await db.delete(followsTable).where(and(eq(followsTable.followerId,req.userId!),eq(followsTable.followingId,Number(req.params.id))));return res.json({following:false})}catch(e){return fail(res,e)}});

socialRouter.get("/notifications",authMiddleware,async(req:AuthedRequest,res)=>{try{return res.json({notifications:await db.select().from(notificationsTable).where(eq(notificationsTable.userId,req.userId!)).orderBy(desc(notificationsTable.createdAt)).limit(100)})}catch(e){return fail(res,e)}});
socialRouter.patch("/notifications/:id/read",authMiddleware,async(req:AuthedRequest,res)=>{try{await db.update(notificationsTable).set({readAt:new Date()}).where(and(eq(notificationsTable.id,Number(req.params.id)),eq(notificationsTable.userId,req.userId!)));return res.json({read:true})}catch(e){return fail(res,e)}});
socialRouter.get("/notifications/stream",authMiddleware,async(req:AuthedRequest,res)=>{res.setHeader("Content-Type","text/event-stream");res.setHeader("Cache-Control","no-cache");res.setHeader("Connection","keep-alive");res.flushHeaders?.();let last=new Date();const timer=setInterval(async()=>{try{const rows=await db.select().from(notificationsTable).where(and(eq(notificationsTable.userId,req.userId!),gt(notificationsTable.createdAt,last)));if(rows.length){last=new Date();res.write(`event: notifications\ndata: ${JSON.stringify(rows)}\n\n`)}}catch{}} ,3000);req.on("close",()=>clearInterval(timer));});

socialRouter.get("/conversations",authMiddleware,async(req:AuthedRequest,res)=>{try{const members=await db.select({conversationId:conversationMembersTable.conversationId,userId:conversationMembersTable.userId,username:usersTable.username,displayName:usersTable.displayName,avatarUrl:usersTable.avatarUrl,updatedAt:conversationsTable.updatedAt}).from(conversationMembersTable).innerJoin(usersTable,eq(usersTable.id,conversationMembersTable.userId)).innerJoin(conversationsTable,eq(conversationsTable.id,conversationMembersTable.conversationId)).where(ne(conversationMembersTable.userId,req.userId!)).orderBy(desc(conversationsTable.updatedAt));return res.json({conversations:members})}catch(e){return fail(res,e)}});
socialRouter.post("/conversations",authMiddleware,async(req:AuthedRequest,res)=>{const userId=Number(req.body?.userId);if(!Number.isInteger(userId)||userId===req.userId)return res.status(400).json({error:"Invalid recipient"});try{const [c]=await db.insert(conversationsTable).values({updatedAt:new Date()}).returning();await db.insert(conversationMembersTable).values([{conversationId:c.id,userId:req.userId!},{conversationId:c.id,userId}]);return res.status(201).json({conversation:c})}catch(e){return fail(res,e)}});
socialRouter.get("/conversations/:id/messages",authMiddleware,async(req:AuthedRequest,res)=>{try{const id=Number(req.params.id);const [member]=await db.select().from(conversationMembersTable).where(and(eq(conversationMembersTable.conversationId,id),eq(conversationMembersTable.userId,req.userId!))).limit(1);if(!member)return res.status(404).json({error:"Conversation not found"});return res.json({messages:(await db.select().from(messagesTable).where(eq(messagesTable.conversationId,id)).orderBy(messagesTable.createdAt).limit(200))})}catch(e){return fail(res,e)}});
socialRouter.post("/conversations/:id/messages",authMiddleware,async(req:AuthedRequest,res)=>{try{const id=Number(req.params.id);const [m]=await db.insert(messagesTable).values({conversationId:id,senderId:req.userId!,body:String(req.body?.body??"").trim(),mediaUrl:req.body?.mediaUrl??null,kind:req.body?.kind??(req.body?.mediaUrl?"image":"text"),durationMs:req.body?.durationMs??null}).returning();await db.update(conversationsTable).set({updatedAt:new Date()}).where(eq(conversationsTable.id,id));return res.status(201).json({message:m})}catch(e){return fail(res,e)}});
socialRouter.get("/conversations/:id/stream",authMiddleware,async(req:AuthedRequest,res)=>{const id=Number(req.params.id);res.setHeader("Content-Type","text/event-stream");res.setHeader("Cache-Control","no-cache");res.setHeader("Connection","keep-alive");res.flushHeaders?.();let last=new Date();const timer=setInterval(async()=>{try{const rows=await db.select().from(messagesTable).where(and(eq(messagesTable.conversationId,id),gt(messagesTable.createdAt,last)));if(rows.length){last=new Date();res.write(`event: messages\ndata: ${JSON.stringify(rows)}\n\n`)}}catch{}} ,2000);req.on("close",()=>clearInterval(timer));});

socialRouter.post("/message-requests",authMiddleware,async(req:AuthedRequest,res)=>{const recipientId=Number(req.body?.recipientId);if(!Number.isInteger(recipientId)||recipientId===req.userId)return res.status(400).json({error:"Invalid recipient"});try{const [blocked]=await db.select().from(blockedUsersTable).where(or(and(eq(blockedUsersTable.blockerId,recipientId),eq(blockedUsersTable.blockedId,req.userId!)),and(eq(blockedUsersTable.blockerId,req.userId!),eq(blockedUsersTable.blockedId,recipientId)))).limit(1);if(blocked)return res.status(403).json({error:"Messaging is blocked"});const [row]=await db.insert(messageRequestsTable).values({senderId:req.userId!,recipientId,message:String(req.body?.message??"").trim(),status:"pending"}).onConflictDoUpdate({target:[messageRequestsTable.senderId,messageRequestsTable.recipientId],set:{message:String(req.body?.message??"").trim(),status:"pending",updatedAt:new Date()}}).returning();return res.status(201).json({request:row})}catch(e){return fail(res,e)}});
socialRouter.get("/message-requests",authMiddleware,async(req:AuthedRequest,res)=>{try{return res.json({requests:await db.select().from(messageRequestsTable).where(or(eq(messageRequestsTable.recipientId,req.userId!),eq(messageRequestsTable.senderId,req.userId!))).orderBy(desc(messageRequestsTable.createdAt))})}catch(e){return fail(res,e)}});
socialRouter.patch("/message-requests/:id",authMiddleware,async(req:AuthedRequest,res)=>{const status=req.body?.status;if(!["accepted","declined","pending"].includes(status))return res.status(400).json({error:"Invalid status"});try{const [row]=await db.update(messageRequestsTable).set({status,updatedAt:new Date()}).where(and(eq(messageRequestsTable.id,Number(req.params.id)),eq(messageRequestsTable.recipientId,req.userId!))).returning();return row?res.json({request:row}):res.status(404).json({error:"Request not found"})}catch(e){return fail(res,e)}});

socialRouter.post("/users/:id/block",authMiddleware,async(req:AuthedRequest,res)=>{try{const id=Number(req.params.id);await db.insert(blockedUsersTable).values({blockerId:req.userId!,blockedId:id}).onConflictDoNothing();await db.delete(followsTable).where(or(and(eq(followsTable.followerId,req.userId!),eq(followsTable.followingId,id)),and(eq(followsTable.followerId,id),eq(followsTable.followingId,req.userId!))));return res.json({blocked:true})}catch(e){return fail(res,e)}});
socialRouter.delete("/users/:id/block",authMiddleware,async(req:AuthedRequest,res)=>{try{await db.delete(blockedUsersTable).where(and(eq(blockedUsersTable.blockerId,req.userId!),eq(blockedUsersTable.blockedId,Number(req.params.id))));return res.json({blocked:false})}catch(e){return fail(res,e)}});
socialRouter.get("/blocked-users",authMiddleware,async(req:AuthedRequest,res)=>{try{return res.json({users:await db.select(publicUser).from(blockedUsersTable).innerJoin(usersTable,eq(usersTable.id,blockedUsersTable.blockedId)).where(eq(blockedUsersTable.blockerId,req.userId!))})}catch(e){return fail(res,e)}});
socialRouter.post("/conversations/:id/archive",authMiddleware,async(req:AuthedRequest,res)=>{try{await db.insert(archivedConversationsTable).values({conversationId:Number(req.params.id),userId:req.userId!}).onConflictDoNothing();return res.json({archived:true})}catch(e){return fail(res,e)}});
socialRouter.delete("/conversations/:id/archive",authMiddleware,async(req:AuthedRequest,res)=>{try{await db.delete(archivedConversationsTable).where(and(eq(archivedConversationsTable.conversationId,Number(req.params.id)),eq(archivedConversationsTable.userId,req.userId!)));return res.json({archived:false})}catch(e){return fail(res,e)}});
socialRouter.get("/conversations/archived",authMiddleware,async(req:AuthedRequest,res)=>{try{return res.json({conversations:await db.select().from(archivedConversationsTable).where(eq(archivedConversationsTable.userId,req.userId!)).orderBy(desc(archivedConversationsTable.archivedAt))})}catch(e){return fail(res,e)}});
socialRouter.post("/account/verify",authMiddleware,async(req:AuthedRequest,res)=>{try{const [v]=await db.update(usersTable).set({verificationStatus:"pending",verificationRequestedAt:new Date()}).where(eq(usersTable.id,req.userId!)).returning({verificationStatus:usersTable.verificationStatus,verificationRequestedAt:usersTable.verificationRequestedAt});return res.json({verification:v})}catch(e){return fail(res,e)}});
export default socialRouter;
