import {useEffect,useRef,useState} from "react";
import {useLocation,useParams} from "wouter";
import {ArrowLeft,Phone,Video,MoreHorizontal,Send,Mic,Square,ImagePlus} from "lucide-react";
import {apiJson,apiFetch} from "@/lib/api";
import {useAuth} from "@/lib/auth-context";
import {subscribeToChat} from "@/lib/realtime";

type User={id:number;username:string;displayName:string;avatarUrl:string|null};
type Msg={id:number;senderId:number;body:string;mediaUrl:string|null;kind:string;createdAt:string};
type Conv={id:number;userId:number;username:string;displayName:string;avatarUrl:string|null;lastMessage:string};

export default function Chat(){
 const [,setLocation]=useLocation();const params=useParams<{userId:string}>();const targetId=Number(params?.userId);const {user:me}=useAuth();
 const [user,setUser]=useState<User|null>(null);const [conv,setConv]=useState<Conv|null>(null);const [messages,setMessages]=useState<Msg[]>([]);const [text,setText]=useState("");const [recording,setRecording]=useState(false);const [sending,setSending]=useState(false);const bottom=useRef<HTMLDivElement>(null);const recorder=useRef<MediaRecorder|null>(null);const chunks=useRef<Blob[]>([]);const fileInput=useRef<HTMLInputElement>(null);
 useEffect(()=>{if(!targetId)return;apiJson<{user:User}>(`/users/${targetId}`).then(d=>setUser(d.user)).catch(()=>{});apiJson<{conversations:Conv[]}>("/conversations").then(d=>{const c=d.conversations.find(x=>x.userId===targetId);if(c)setConv(c);else apiJson<{conversation:{id:number}}>("/conversations",{method:"POST",body:JSON.stringify({userId:targetId})}).then(x=>setConv({id:x.conversation.id,userId:targetId,username:"",displayName:"",avatarUrl:null,lastMessage:""})).catch(()=>{});}).catch(()=>{});},[targetId]);
 useEffect(()=>{if(!conv)return;let active=true;const load=async()=>{const d=await apiJson<{messages:Msg[]}>(`/conversations/${conv.id}/messages`).catch(()=>({messages:[]}));if(active)setMessages(d.messages);};load();const timer=window.setInterval(load,2500);let close=()=>{};try{close=subscribeToChat(conv.id,data=>{const m=data as Msg;if(m?.id)setMessages(old=>old.some(x=>x.id===m.id)?old:[...old,m]);});}catch{}return()=>{active=false;window.clearInterval(timer);close()};},[conv?.id]);
 useEffect(()=>bottom.current?.scrollIntoView({behavior:"smooth"}),[messages]);
 const send=async(body:string,kind="text",mediaUrl?:string)=>{if(!body.trim()&&!mediaUrl||!conv||!me)return;setSending(true);const d=await apiJson<{message:Msg}>(`/conversations/${conv.id}/messages`,{method:"POST",body:JSON.stringify({body,kind,mediaUrl:mediaUrl??null})}).catch(()=>null);if(d?.message)setMessages(m=>m.some(x=>x.id===d.message.id)?m:[...m,d.message]);setSending(false)};
 const startRecording=async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const r=new MediaRecorder(stream);chunks.current=[];r.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};r.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks.current,{type:r.mimeType||"audio/webm"});const data=await blobToDataUrl(blob);await send("Voice message","audio",data)};recorder.current=r;r.start();setRecording(true)}catch{setRecording(false)}};
 const stopRecording=()=>{recorder.current?.stop();recorder.current=null;setRecording(false)};
 const uploadPhoto=async(file:File)=>{if(!file||!conv)return;const data=await fileToDataUrl(file);await send("Photo","image",data)};
 const av=user?.avatarUrl??`https://api.dicebear.com/8.x/initials/svg?seed=${encodeURIComponent(user?.displayName??"U")}&backgroundColor=FF006E`;
 return <div className="w-full max-w-[430px] mx-auto min-h-screen bg-background flex flex-col"><header className="sticky top-0 z-40 px-4 py-3 flex items-center gap-3 bg-black/95 border-b border-white/5"><button onClick={()=>setLocation("/messages")}><ArrowLeft size={22} className="text-white/80"/></button><img src={av} className="w-9 h-9 rounded-full object-cover"/><div className="flex-1"><b className="text-white text-sm">{user?.displayName??"User"}</b><p className="text-white/40 text-xs">@{user?.username??""}</p></div><button onClick={()=>setLocation(`/voice-call/${targetId}`)}><Phone size={20} className="text-white/70"/></button><button onClick={()=>setLocation(`/video-call/${targetId}`)}><Video size={20} className="text-white/70"/></button><MoreHorizontal size={20} className="text-white/70"/></header><div className="flex-1 overflow-y-auto px-3 py-4 pb-24">{messages.map(m=>{const mine=m.senderId===me?.id;return <div key={m.id} className={`flex mb-2 ${mine?"justify-end":"justify-start"}`}><div className={`max-w-[78%] px-3.5 py-2.5 rounded-2xl text-sm ${mine?"rounded-br-sm text-white bg-gradient-to-r from-pink-500 to-purple-600":"rounded-bl-sm text-white/90 bg-white/[.08]"}`}>{m.kind==="image"&&m.mediaUrl?<img src={m.mediaUrl} className="max-w-full rounded-xl mb-1"/>:m.kind==="audio"&&m.mediaUrl?<audio controls src={m.mediaUrl} className="max-w-full"/>:<span>{m.body}</span>}</div></div>})}<div ref={bottom}/></div><input ref={fileInput} type="file" accept="image/*" hidden onChange={e=>{const f=e.target.files?.[0];if(f)uploadPhoto(f);e.currentTarget.value=""}}/><div className="fixed bottom-0 left-1/2 -translate-x-1/2 w-full max-w-[430px] px-3 py-3 bg-black/95 border-t border-white/5"><div className="flex gap-2 items-center"><button onClick={()=>fileInput.current?.click()} disabled={sending}><ImagePlus size={21} className="text-pink-400"/></button><button onClick={recording?stopRecording:startRecording} disabled={sending}>{recording?<Square size={21} className="text-red-400"/>:<Mic size={21} className="text-pink-400"/>}</button><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){send(text);setText("")}}} placeholder={recording?"Recording…":"Message..."} disabled={recording||sending} className="flex-1 bg-white/[.07] rounded-full px-4 py-3 text-white outline-none"/><button onClick={()=>{send(text);setText("")}} disabled={sending||!text.trim()} className="w-10 h-10 rounded-full flex items-center justify-center bg-gradient-to-r from-pink-500 to-purple-600"><Send size={16} className="text-white"/></button></div></div></div>;
}
async function blobToDataUrl(blob:Blob){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(blob)})}
async function fileToDataUrl(file:File){return blobToDataUrl(file)}
