import { useState, useEffect, useRef, useCallback } from "react";
import { useLocation } from "wouter";
import { Search, UserPlus, Globe, ChevronDown, Bookmark, Share2, Flag, EyeOff, WifiOff, Radio } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { type Post } from "@/types/domain";
import StoryAvatar from "@/components/StoryAvatar";
import PostCard, { type LiveAuthor } from "@/components/PostCard";
import BottomNav from "@/components/BottomNav";
import { t } from "@/lib/i18n";
import { useAuth } from "@/lib/auth-context";
import { apiFetch } from "@/lib/api";

const HEADER_H = 56;
const STORIES_H = 78;
const NAV_H = 64;
const TOP_OFFSET = HEADER_H + STORIES_H;
const SCROLL_KEY = "yuniko_feed_scroll";
const POLL_INTERVAL = 30_000;
const LIVE_ENABLED = import.meta.env.VITE_LIVE_ENABLED === "true";

function useOnlineStatus() {
  const [isOnline, setIsOnline] = useState(() => navigator.onLine);
  useEffect(() => { const on=()=>setIsOnline(true), off=()=>setIsOnline(false); window.addEventListener("online",on); window.addEventListener("offline",off); return()=>{window.removeEventListener("online",on);window.removeEventListener("offline",off)}; }, []);
  return isOnline;
}
interface LiveFeedPost { post: Post; author: LiveAuthor }
interface LiveStory { id:number; userId:number; mediaUrl:string; caption:string; authorDisplayName:string; authorUsername:string; authorAvatarUrl:string|null }
function relativeTime(iso:string){const diff=Date.now()-new Date(iso).getTime(),m=Math.floor(diff/60000);if(m<1)return"just now";if(m<60)return`${m}m`;const h=Math.floor(m/60);if(h<24)return`${h}h`;return`${Math.floor(h/24)}d`}

export default function Home(){
  const [,setLocation]=useLocation(); const {token}=useAuth(); const isOnline=useOnlineStatus(); const scrollRef=useRef<HTMLDivElement>(null);
  const [optionsPostId,setOptionsPostId]=useState<string|null>(null); const [worldFeedOpen,setWorldFeedOpen]=useState(false);
  const [livePosts,setLivePosts]=useState<LiveFeedPost[]>([]); const [liveStories,setLiveStories]=useState<LiveStory[]>([]);
  const [newPostsBadge,setNewPostsBadge]=useState(0); const [nextCursor,setNextCursor]=useState<number|null>(null); const [hasMore,setHasMore]=useState(true); const [loadingMore,setLoadingMore]=useState(false);
  const [hiddenPostIds,setHiddenPostIds]=useState<Set<number>>(new Set());
  const selectedPostId=optionsPostId?.startsWith("live_")?Number(optionsPostId.slice(5)):NaN;
  const closeOptions=()=>setOptionsPostId(null);
  const convert=(p:any):LiveFeedPost=>({post:{id:`live_${p.id}`,userId:`live_${p.userId}`,imageUrl:p.mediaUrl??"",mediaType:p.mediaType??"text",mediaItems:p.mediaItems?JSON.parse(p.mediaItems):undefined,caption:p.caption??"",hashtags:p.hashtags?p.hashtags.split(/[\s,]+/).filter(Boolean):[],likes:p.likes??0,comments:p.comments??0,shares:p.shares??0,saves:p.saves??0,timestamp:relativeTime(p.createdAt),isLiked:Boolean(p.liked),isSaved:Boolean(p.saved),location:p.location??undefined} satisfies Post,author:{displayName:p.authorDisplayName,username:p.authorUsername,avatarUrl:p.authorAvatarUrl}});
  const fetchHidden=useCallback(async()=>{if(!token)return;const d=await apiFetch("/account/settings").then(r=>r.ok?r.json():null).catch(()=>null);if(d?.settings?.hiddenPostIds){try{const ids=JSON.parse(d.settings.hiddenPostIds);if(Array.isArray(ids))setHiddenPostIds(new Set(ids.map(Number).filter(Number.isFinite)))}catch{}}},[token]);
  const fetchFeed=useCallback(async(isBackground=false,cursor:number|null=null)=>{if(!token)return;try{const q=cursor?`?cursor=${cursor}&limit=20`:"?limit=20";const res=await fetch(`/api/posts/feed${q}`,{headers:{Authorization:`Bearer ${token}`}});if(!res.ok)return;const d=await res.json() as {posts?:any[];nextCursor?:number|null;hasMore?:boolean};const converted=(d.posts??[]).map(convert).filter(x=>{const id=Number(String(x.post.id).replace("live_",""));return !hiddenPostIds.has(id)});if(cursor){setLivePosts(prev=>{const ids=new Set(prev.map(x=>x.post.id));return [...prev,...converted.filter(x=>!ids.has(x.post.id))]})}else if(isBackground){setLivePosts(prev=>{const ids=new Set(prev.map(x=>x.post.id));const fresh=converted.filter(x=>!ids.has(x.post.id));if(fresh.length)setNewPostsBadge(b=>b+fresh.length);return [...fresh,...prev]})}else{setLivePosts(converted);setNewPostsBadge(0)}setNextCursor(d.nextCursor??null);setHasMore(Boolean(d.hasMore));}catch{/* keep current feed */}},[token,hiddenPostIds]);
  const loadMore=useCallback(async()=>{if(loadingMore||!hasMore||nextCursor===null)return;setLoadingMore(true);try{await fetchFeed(false,nextCursor)}finally{setLoadingMore(false)}},[loadingMore,hasMore,nextCursor,fetchFeed]);
  const fetchStories=useCallback(async()=>{if(!token)return;try{const res=await fetch("/api/stories",{headers:{Authorization:`Bearer ${token}`}});if(res.ok){const d=await res.json();if(d.stories)setLiveStories(d.stories)}}catch{}},[token]);
  useEffect(()=>{fetchHidden();},[fetchHidden]);
  useEffect(()=>{fetchFeed(false);fetchStories()},[fetchFeed,fetchStories]);
  useEffect(()=>{const id=setInterval(()=>{fetchFeed(true);fetchStories()},POLL_INTERVAL);return()=>clearInterval(id)},[fetchFeed,fetchStories]);
  useEffect(()=>{const onVisible=()=>{if(document.visibilityState==="visible"){fetchFeed(true);fetchStories();fetchHidden()}};document.addEventListener("visibilitychange",onVisible);return()=>document.removeEventListener("visibilitychange",onVisible)},[fetchFeed,fetchStories,fetchHidden]);
  useEffect(()=>{const el=scrollRef.current;if(!el)return;const saved=sessionStorage.getItem(SCROLL_KEY);if(saved){const top=parseInt(saved,10);if(!Number.isNaN(top)&&top>0)requestAnimationFrame(()=>el.scrollTo({top,behavior:"instant"}))}const onScroll=()=>{sessionStorage.setItem(SCROLL_KEY,String(el.scrollTop));if(el.scrollHeight-el.scrollTop-el.clientHeight<Math.max(700,el.clientHeight*1.5))void loadMore()};el.addEventListener("scroll",onScroll,{passive:true});return()=>el.removeEventListener("scroll",onScroll)},[loadMore]);
  const saveSelectedPost=async()=>{if(!Number.isFinite(selectedPostId))return closeOptions();await apiFetch(`/posts/${selectedPostId}/save`,{method:"POST"}).catch(()=>{});closeOptions()};
  const shareSelectedPost=async()=>{if(!Number.isFinite(selectedPostId))return closeOptions();const url=`${window.location.origin}/post/${selectedPostId}`;if(navigator.share)await navigator.share({title:"Yuniko post",url}).catch(()=>undefined);else await navigator.clipboard?.writeText(url).catch(()=>undefined);await apiFetch(`/posts/${selectedPostId}/share`,{method:"POST"}).catch(()=>{});closeOptions()};
  const reportSelectedPost=async()=>{if(!Number.isFinite(selectedPostId))return closeOptions();await apiFetch(`/posts/${selectedPostId}/report`,{method:"POST"}).catch(()=>{});closeOptions()};
  const hideSelectedPost=async()=>{if(!Number.isFinite(selectedPostId))return closeOptions();const ok=await apiFetch(`/posts/${selectedPostId}/hide`,{method:"POST"}).then(r=>r.ok).catch(()=>false);if(ok){setHiddenPostIds(prev=>new Set([...prev,selectedPostId]));setLivePosts(prev=>prev.filter(x=>x.post.id!==optionsPostId))}closeOptions()};
  const allFeedItems=livePosts.map(({post,author})=>({post,author}));
  const handleNewPostsBanner=()=>{fetchFeed(false);fetchStories();setNewPostsBadge(0);scrollRef.current?.scrollTo({top:0,behavior:"smooth"});sessionStorage.setItem(SCROLL_KEY,"0")};
  return <div className="relative w-full max-w-[430px] mx-auto" style={{height:"100dvh",overflow:"hidden"}}>
    <header className="absolute inset-x-0 top-0 z-50 flex items-center justify-between px-4" style={{height:HEADER_H,background:"rgba(10,8,18,0.88)",backdropFilter:"blur(20px)",borderBottom:"1px solid rgba(255,61,154,0.1)"}}><button onClick={()=>scrollRef.current?.scrollTo({top:0,behavior:"smooth"})}><span className="text-2xl font-black tracking-tight" style={{background:"linear-gradient(90deg,#FF3D9A,#C026D3,#8B00FF)",WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent"}}>Yuniko</span></button><button onClick={()=>setWorldFeedOpen(p=>!p)} className="flex items-center gap-1.5 px-3 py-1.5 rounded-full" style={{background:"rgba(255,255,255,.06)",border:"1px solid rgba(255,61,154,.3)"}} data-testid="btn-world-feed"><Globe size={13} style={{color:"#FF3D9A"}}/><span className="text-white/90 text-sm font-medium">{t("worldFeed")}</span><ChevronDown size={12} className="text-white/55"/></button><div className="flex items-center gap-3"><motion.button whileTap={{scale:.85}} onClick={()=>setLocation("/search")}><Search size={21} className="text-white/75"/></motion.button><motion.button whileTap={{scale:.85}} onClick={()=>setLocation("/add-friends")}><UserPlus size={21} className="text-white/75"/></motion.button></div></header>
    <AnimatePresence>{worldFeedOpen&&<><motion.div key="wf-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="absolute inset-0 z-40" onClick={()=>setWorldFeedOpen(false)}/><motion.div key="wf-menu" initial={{opacity:0,y:-8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}} className="absolute top-[60px] left-1/2 -translate-x-1/2 w-44 rounded-2xl z-50 overflow-hidden" style={{background:"rgba(18,14,30,.98)",border:"1px solid rgba(255,61,154,.25)"}}><button onClick={()=>setWorldFeedOpen(false)} className="w-full px-4 py-3 text-left text-white/85 text-sm flex items-center gap-2"><Globe size={13} style={{color:"#FF3D9A"}}/>World Feed</button></motion.div></>}</AnimatePresence>
    <div className="absolute inset-x-0 z-40" style={{top:HEADER_H,height:STORIES_H,background:"rgba(10,8,18,.82)",backdropFilter:"blur(12px)",borderBottom:"1px solid rgba(255,255,255,.05)"}}><div className="flex items-center gap-3 h-full px-4 overflow-x-auto no-scrollbar"><StoryAvatar userId="me" isOwn />{LIVE_ENABLED&&<button onClick={()=>setLocation("/live")} className="flex-shrink-0 flex flex-col items-center gap-1.5" data-testid="btn-go-live-stories"><div className="w-14 h-14 rounded-full flex items-center justify-center relative" style={{background:"linear-gradient(135deg,#FF006E,#8B00FF)"}}><Radio size={22} className="text-white"/><div className="absolute -top-0.5 -right-0.5 px-1 py-0.5 rounded-full text-[8px] font-bold text-white" style={{background:"#FF006E"}}>LIVE</div></div><span className="text-white/60 text-[10px]">Go Live</span></button>}{liveStories.map(story=><LiveStoryAvatar key={`ls_${story.id}`} story={story}/>)}</div></div>
    <AnimatePresence>{newPostsBadge>0&&<motion.button key="new-posts" initial={{opacity:0,y:-8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}} onClick={handleNewPostsBanner} className="absolute z-50 left-1/2 -translate-x-1/2 px-4 py-2 rounded-full text-white text-xs font-semibold" style={{top:TOP_OFFSET+10,background:"linear-gradient(135deg,#FF006E,#8B00FF)"}}>↑ {newPostsBadge} new post{newPostsBadge>1?"s":""}</motion.button>}{!isOnline&&<motion.div key="offline" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="absolute inset-x-0 z-30 flex items-center justify-center gap-1.5 py-1.5" style={{top:TOP_OFFSET,background:"rgba(239,68,68,.88)"}}><WifiOff size={12} className="text-white"/><span className="text-white text-xs">Offline — showing cached posts</span></motion.div>}</AnimatePresence>
    <div ref={scrollRef} className="absolute inset-x-0 overflow-y-scroll" style={{top:TOP_OFFSET,bottom:NAV_H,scrollSnapType:"y mandatory",scrollSnapStop:"always",WebkitOverflowScrolling:"touch",overscrollBehaviorY:"contain"}} data-testid="posts-feed">
      {allFeedItems.length===0?<div className="h-full flex flex-col items-center justify-center px-8 text-center"><div className="w-16 h-16 rounded-full flex items-center justify-center mb-4" style={{background:"linear-gradient(135deg,#FF006E,#8B00FF)"}}><Globe size={26} className="text-white"/></div><h2 className="text-white text-xl font-black mb-2">Your world feed is ready</h2><p className="text-white/55 text-sm leading-relaxed mb-5">Real Yuniko posts appear here — no sample content.</p><button onClick={()=>setLocation("/create")} className="px-5 py-3 rounded-2xl text-white text-sm font-bold" style={{background:"linear-gradient(135deg,#FF006E,#8B00FF)"}}>Create a post</button></div>:allFeedItems.map(({post,author})=><div key={post.id} className="relative px-2.5" style={{height:`calc(100dvh - ${TOP_OFFSET}px - ${NAV_H}px)`,scrollSnapAlign:"start",scrollSnapStop:"always",paddingBottom:10,flexShrink:0}}><div className="relative w-full h-full rounded-[20px] overflow-hidden"><PostCard post={post} liveAuthor={author} onOptions={post.isSponsored?undefined:()=>setOptionsPostId(post.id)}/></div></div>)}
      {loadingMore&&<div className="py-5 text-center text-white/40 text-xs">{t("loadingMore")}</div>}{!hasMore&&allFeedItems.length>0&&<div className="py-5 text-center text-white/25 text-xs">End of World Feed</div>}
    </div>
    <BottomNav/>
    <AnimatePresence>{optionsPostId&&<><motion.div key="options-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-50 bg-black/65" onClick={closeOptions}/><motion.div key="options-sheet" initial={{y:"100%"}} animate={{y:0}} exit={{y:"100%"}} transition={{type:"spring",damping:28,stiffness:340}} className="fixed bottom-0 left-1/2 -translate-x-1/2 w-full max-w-[430px] z-50 rounded-t-2xl overflow-hidden" style={{background:"rgba(16,12,28,.98)"}}><div className="w-10 h-1 rounded-full bg-white/18 mx-auto mt-3 mb-4"/><button onClick={saveSelectedPost} className="w-full flex items-center gap-3 px-5 py-4 text-white/85 text-sm" style={{borderBottom:"1px solid rgba(255,255,255,.06)"}}><Bookmark size={18}/>{t("savePost")}</button><button onClick={shareSelectedPost} className="w-full flex items-center gap-3 px-5 py-4 text-white/85 text-sm" style={{borderBottom:"1px solid rgba(255,255,255,.06)"}}><Share2 size={18}/>{t("sharePost")}</button><button onClick={hideSelectedPost} className="w-full flex items-center gap-3 px-5 py-4 text-white/85 text-sm" style={{borderBottom:"1px solid rgba(255,255,255,.06)"}}><EyeOff size={18}/>{t("hide")}</button><button onClick={reportSelectedPost} className="w-full flex items-center gap-3 px-5 py-4 text-red-400 text-sm" style={{borderBottom:"1px solid rgba(255,255,255,.06)"}}><Flag size={18}/>{t("report")}</button><button onClick={closeOptions} className="w-full py-4 text-white/45 text-sm">{t("cancel")}</button></motion.div></>}</AnimatePresence>
  </div>
}
function LiveStoryAvatar({story}:{story:LiveStory}){const[,setLocation]=useLocation();const avatarSrc=story.authorAvatarUrl??`https://api.dicebear.com/8.x/initials/svg?seed=${encodeURIComponent(story.authorDisplayName)}&backgroundColor=FF006E`;return <motion.button onClick={()=>setLocation(`/story/live_${story.id}`)} className="flex flex-col items-center gap-1 flex-shrink-0" style={{minWidth:64}} whileTap={{scale:.9}}><div className="relative"><div className="w-[54px] h-[54px] rounded-full p-[2px]" style={{background:"linear-gradient(135deg,#FF006E,#8B00FF)"}}><img src={avatarSrc} alt={story.authorDisplayName} className="w-full h-full rounded-full object-cover" loading="lazy"/></div></div><span className="text-white/70 text-[10px] font-medium truncate max-w-[60px]">{story.authorDisplayName}</span></motion.button>}
