import {useEffect,useRef,useState} from "react";
import {useLocation} from "wouter";
import {X,Users,Heart,MessageCircle,Share2,Mic,MicOff,Video,VideoOff} from "lucide-react";
import {useAuth} from "@/lib/auth-context";
const fmt=(s:number)=>`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`;
export default function Live(){const [,setLocation]=useLocation();const {user}=useAuth();const videoRef=useRef<HTMLVideoElement>(null);const streamRef=useRef<MediaStream|null>(null);const [isLive,setIsLive]=useState(false);const [micOn,setMicOn]=useState(true);const [camOn,setCamOn]=useState(true);const [duration,setDuration]=useState(0);const [comment,setComment]=useState("");const [comments,setComments]=useState<{id:number,text:string}[]>([]);const [likes,setLikes]=useState(0);
 useEffect(()=>{if(!isLive)return;const id=window.setInterval(()=>setDuration(v=>v+1),1000);return()=>window.clearInterval(id)},[isLive]);
 useEffect(()=>{return()=>{streamRef.current?.getTracks().forEach(t=>t.stop())}},[]);
 const start=async()=>{try{const s=await navigator.mediaDevices.getUserMedia({video:true,audio:true});streamRef.current=s;if(videoRef.current){videoRef.current.srcObject=s;await videoRef.current.play().catch(()=>{})}setIsLive(true);}catch{setIsLive(false)}};
 const stop=()=>{streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;setIsLive(false);setDuration(0);};
 const toggleMic=()=>{const t=streamRef.current?.getAudioTracks()[0];if(t){t.enabled=!t.enabled;setMicOn(t.enabled)}};const toggleCam=()=>{const t=streamRef.current?.getVideoTracks()[0];if(t){t.enabled=!t.enabled;setCamOn(t.enabled)}};const send=()=>{const text=comment.trim();if(!text)return;setComments(c=>[...c,{id:Date.now(),text}].slice(-30));setComment("");};
 return <div className="w-full max-w-[430px] mx-auto min-h-screen bg-black text-white relative overflow-hidden"><video ref={videoRef} muted playsInline className="absolute inset-0 w-full h-full object-cover"/><div className="absolute inset-0 bg-gradient-to-b from-black/60 via-transparent to-black/80"/><header className="absolute top-0 left-0 right-0 z-10 p-4 flex items-center gap-3"><button onClick={()=>{stop();setLocation("/")}}><X/></button><div className="flex-1"><b>{user?.displayName??"You"}</b><p className="text-white/50 text-xs">@{user?.username??"you"}</p></div>{isLive&&<span className="px-2 py-1 rounded-full bg-red-500 text-xs font-bold">LIVE {fmt(duration)}</span>}</header><div className="absolute top-20 left-4 z-10 flex gap-2"><span className="px-3 py-1.5 rounded-full bg-black/40 text-xs flex gap-1 items-center"><Users size={14}/> Real viewers connect when the live transport is configured</span></div>{isLive&&<div className="absolute right-4 bottom-32 z-10 flex flex-col gap-3"><button onClick={()=>setLikes(v=>v+1)} className="w-11 h-11 rounded-full bg-black/40 flex items-center justify-center"><Heart className="text-pink-400" fill="currentColor"/></button><button className="w-11 h-11 rounded-full bg-black/40 flex items-center justify-center"><Share2/></button></div>}<div className="absolute bottom-0 left-0 right-0 z-10 p-4 pb-7"><div className="max-h-36 overflow-y-auto mb-3 space-y-1">{comments.map(c=><p key={c.id} className="text-sm"><span className="font-semibold">{user?.username??"You"}</span> <span className="text-white/80">{c.text}</span></p>)}</div>{isLive&&<div className="flex gap-2 mb-3"><input value={comment} onChange={e=>setComment(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Say something..." className="flex-1 rounded-full bg-black/50 border border-white/10 px-4 py-3 outline-none"/><button onClick={send} className="w-11 h-11 rounded-full bg-gradient-to-r from-pink-500 to-purple-600 flex items-center justify-center"><MessageCircle size={18}/></button></div>}<div className="flex items-center gap-3"><button onClick={toggleMic} disabled={!isLive} className="w-11 h-11 rounded-full bg-white/10 flex items-center justify-center">{micOn?<Mic/>:<MicOff/>}</button><button onClick={toggleCam} disabled={!isLive} className="w-11 h-11 rounded-full bg-white/10 flex items-center justify-center">{camOn?<Video/>:<VideoOff/>}</button>{!isLive?<button onClick={start} className="flex-1 py-3 rounded-full bg-gradient-to-r from-pink-500 to-purple-600 font-semibold">Start Live</button>:<button onClick={stop} className="flex-1 py-3 rounded-full bg-red-500 font-semibold">End Live</button>}</div><p className="text-center text-white/30 text-[11px] mt-2">Live media transport/WebRTC signaling must be enabled for other users to receive this stream.</p></div></div>;
}
