import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { ArrowLeft, MessageCircle } from "lucide-react";
import { apiJson } from "@/lib/api";
import { t } from "@/lib/i18n";
import BottomNav from "@/components/BottomNav";
type MessageRequest={id:number;user:{id:number;username:string;displayName:string;avatarUrl:string|null;verified:boolean};message:string;timestamp:string|null};
function formatTime(value:string|null){if(!value)return "";const date=new Date(value);if(Number.isNaN(date.getTime()))return "";const diff=Date.now()-date.getTime();if(diff<60000)return "now";if(diff<3600000)return Math.floor(diff/60000)+"m";if(diff<86400000)return Math.floor(diff/3600000)+"h";return date.toLocaleDateString([],{day:"2-digit",month:"2-digit"});}
const GRADIENT="linear-gradient(135deg,#FF006E 0%,#8B00FF 100%)";
export default function MessageRequests(){
 const [,setLocation]=useLocation();const [requests,setRequests]=useState<MessageRequest[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [actionId,setActionId]=useState<number|null>(null);
 const load=()=>{setLoading(true);setError(null);void apiJson<{requests:MessageRequest[]}>("/message-requests").then(data=>setRequests(data.requests??[])).catch(err=>setError(err instanceof Error?err.message:"Unable to load message requests")).finally(()=>setLoading(false));};
 useEffect(()=>{load();},[]);
 const accept=async(request:MessageRequest)=>{setActionId(request.id);try{const data=await apiJson<{conversationId:number;userId:number}>("/message-requests/"+request.id+"/accept",{method:"POST"});setRequests(current=>current.filter(item=>item.id!==request.id));setLocation("/chat/"+data.userId);}catch(err){setError(err instanceof Error?err.message:"Unable to accept request");}finally{setActionId(null);}};
 const decline=async(request:MessageRequest)=>{setActionId(request.id);try{await apiJson("/message-requests/"+request.id,{method:"DELETE"});setRequests(current=>current.filter(item=>item.id!==request.id));}catch(err){setError(err instanceof Error?err.message:"Unable to decline request");}finally{setActionId(null);}};
 return <div className="w-full max-w-[430px] mx-auto min-h-screen bg-background pb-20"><header className="sticky top-0 z-40 px-4 py-4 flex items-center gap-3" style={{background:"rgba(13,11,20,0.95)",backdropFilter:"blur(20px)",borderBottom:"1px solid rgba(255,255,255,0.06)"}} data-testid="message-requests-header"><button onClick={()=>setLocation("/messages")} data-testid="btn-back-requests"><ArrowLeft size={22} className="text-white/80"/></button><h1 className="text-base font-semibold text-white">{t("messageRequests")}</h1></header>
 <div className="px-4 py-3"><p className="text-white/40 text-sm mb-4">People you don\'t follow will appear here. They won\'t know you\'ve seen their requests until you accept.</p>
 {error&&<div className="mb-3 rounded-xl px-3 py-2 text-sm text-red-300/80" style={{background:"rgba(255,80,100,0.08)"}}>{error}<button onClick={load} className="ml-2 underline text-white/70">Retry</button></div>}
 {loading?<div className="py-16 text-center text-white/35 text-sm">Loading...</div>:requests.length===0?<div className="flex flex-col items-center justify-center py-16 gap-3"><MessageCircle size={40} className="text-white/20"/><p className="text-white/40 text-sm">No message requests</p></div>:requests.map(req=><div key={req.id} className="p-4 rounded-2xl mb-3" style={{background:"rgba(255,255,255,0.04)",border:"1px solid rgba(255,255,255,0.07)"}} data-testid={"message-request-"+req.id}><div className="flex items-center gap-3 mb-3"><button onClick={()=>setLocation("/user/"+req.user.id)}><img src={req.user.avatarUrl||("https://api.dicebear.com/9.x/initials/svg?seed="+encodeURIComponent(req.user.displayName))} alt={req.user.displayName} className="w-10 h-10 rounded-full object-cover"/></button><div className="flex-1 min-w-0"><p className="text-white font-semibold text-sm truncate">{req.user.displayName}</p><p className="text-white/40 text-xs">@{req.user.username} · {formatTime(req.timestamp)}</p></div></div>
 <p className="text-white/70 text-sm mb-3 line-clamp-2">{req.message}</p><div className="flex gap-2"><button disabled={actionId===req.id} onClick={()=>void accept(req)} className="flex-1 py-2 rounded-xl text-sm font-semibold text-white disabled:opacity-50" style={{background:GRADIENT,boxShadow:"0 2px 8px rgba(255,0,110,0.3)"}} data-testid={"btn-accept-request-"+req.id}>{actionId===req.id?"...":t("accept")}</button><button disabled={actionId===req.id} onClick={()=>void decline(req)} className="flex-1 py-2 rounded-xl text-sm font-semibold text-white/60 disabled:opacity-50" style={{background:"rgba(255,255,255,0.08)"}} data-testid={"btn-decline-request-"+req.id}>{t("decline")}</button></div></div>)}
 </div><BottomNav/></div>;
}