import { useState, useEffect, useRef } from "react";
import { useLocation, useParams } from "wouter";
import { X, Send, MoreHorizontal, BadgeCheck } from "lucide-react";
import { apiJson } from "@/lib/api";
import { useAuth } from "@/lib/auth-context";
import { t } from "@/lib/i18n";

const QUICK_REACTIONS = ["❤️", "😂", "😮", "😢", "🔥", "👏"];
type Story = { id:number; userId:number; mediaUrl:string; caption:string; createdAt:string; authorDisplayName:string; authorUsername:string; authorAvatarUrl:string|null; viewed?:boolean };

export default function StoryViewer() {
  const [, setLocation] = useLocation(); const params = useParams<{ userId: string }>(); const { user: me } = useAuth();
  const routeId = params?.userId ?? ""; const [stories, setStories] = useState<Story[]>([]); const [currentIndex, setCurrentIndex] = useState(0); const [progress, setProgress] = useState(0); const [paused, setPaused] = useState(false); const [replyText, setReplyText] = useState(""); const [reactionShown, setReactionShown] = useState<string | null>(null); const intervalRef = useRef<number | null>(null);
  useEffect(() => { let cancelled=false; (async()=>{try{const data=await apiJson<{stories:Story[]}>("/stories");if(cancelled)return;const numeric=routeId.startsWith("live_")?Number(routeId.slice(5)):Number(routeId);const targetUserId=routeId.startsWith("live_")?data.stories.find(s=>s.id===numeric)?.userId:numeric;setStories(data.stories.filter(s=>s.userId===targetUserId));setCurrentIndex(0);}catch{setStories([]);}})();return()=>{cancelled=true;};},[routeId]);
  const currentStory=stories[currentIndex];
  useEffect(()=>{if(!currentStory||paused)return;intervalRef.current=window.setInterval(()=>setProgress(prev=>{if(prev>=100){if(currentIndex<stories.length-1){setCurrentIndex(i=>i+1);return 0;}setLocation("/");return 100;}return prev+2;}),100);return()=>{if(intervalRef.current)window.clearInterval(intervalRef.current);};},[currentIndex,paused,stories.length,currentStory,setLocation]);
  useEffect(()=>{if(!currentStory)return;apiJson(`/stories/${currentStory.id}/view`,{method:"POST"}).catch(()=>undefined);},[currentStory?.id]);
  const goNext=()=>{if(currentIndex<stories.length-1){setCurrentIndex(i=>i+1);setProgress(0);}else setLocation("/");}; const goPrev=()=>{if(currentIndex>0){setCurrentIndex(i=>i-1);setProgress(0);}};
  const handleReaction=(emoji:string)=>{setReactionShown(emoji);if(currentStory)apiJson(`/stories/${currentStory.id}/reaction`,{method:"POST",body:JSON.stringify({emoji})}).catch(()=>{});window.setTimeout(()=>setReactionShown(null),1500);};
  const sendReply=async()=>{const text=replyText.trim();if(!text||!currentStory)return;await apiJson(`/stories/${currentStory.id}/replies`,{method:"POST",body:JSON.stringify({text})}).catch(()=>{});setReplyText("");};
  if(!currentStory)return <div className="w-full max-w-[430px] mx-auto min-h-screen bg-black flex items-center justify-center"><div className="text-center"><p className="text-white/50">{t("noStories")}</p><button onClick={()=>setLocation("/")} className="mt-4" style={{color:"#FF3D9A"}}>{t("back")}</button></div></div>;
  const avatar=currentStory.authorAvatarUrl??`https://api.dicebear.com/8.x/initials/svg?seed=${encodeURIComponent(currentStory.authorDisplayName)}&backgroundColor=FF006E`;
  return <div className="w-full max-w-[430px] mx-auto min-h-screen relative overflow-hidden bg-black" data-testid="story-viewer"><img src={currentStory.mediaUrl} alt={currentStory.caption||"Story"} className="absolute inset-0 w-full h-full object-cover" onPointerDown={()=>setPaused(true)} onPointerUp={()=>setPaused(false)}/><div className="absolute inset-0 flex z-10"><div className="flex-1" onClick={goPrev}/><div className="flex-1" onClick={goNext}/></div><div className="absolute top-4 left-3 right-3 z-20 flex gap-1">{stories.map((_,i)=><div key={i} className="flex-1 h-1 rounded-full overflow-hidden bg-white/30"><div className="h-full bg-white/90" style={{width:i<currentIndex?"100":i===currentIndex?`${progress}%`:"0%"}}/></div>)}</div><div className="absolute top-10 left-3 right-3 z-20 flex items-center justify-between"><button onClick={()=>setLocation(`/user/${currentStory.userId}`)} className="flex items-center gap-2"><img src={avatar} className="w-9 h-9 rounded-full object-cover border-2 border-pink-500"/><div><div className="flex items-center gap-1"><span className="text-white font-semibold text-sm">{currentStory.authorDisplayName}</span><BadgeCheck size={13} className="text-blue-300"/></div><span className="text-white/60 text-xs">{new Date(currentStory.createdAt).toLocaleDateString()}</span></div></button><div className="flex gap-3"><button><MoreHorizontal size={22} className="text-white"/></button><button onClick={()=>setLocation("/")}><X size={22} className="text-white"/></button></div></div>{reactionShown&&<div className="absolute inset-0 z-30 flex items-center justify-center pointer-events-none"><span className="text-7xl animate-bounce">{reactionShown}</span></div>}<div className="absolute bottom-24 left-3 right-3 z-20 flex justify-center gap-3">{QUICK_REACTIONS.map(e=><button key={e} onClick={()=>handleReaction(e)} className="text-2xl p-1 rounded-full bg-white/10">{e}</button>)}</div><div className="absolute bottom-6 left-3 right-3 z-20 flex items-center gap-2"><div className="flex-1 flex items-center px-4 py-2.5 rounded-full bg-white/10 border border-white/20"><input value={replyText} onChange={e=>setReplyText(e.target.value)} onKeyDown={e=>e.key==="Enter"&&sendReply()} placeholder={`Reply to ${currentStory.authorDisplayName}...`} className="flex-1 bg-transparent text-white text-sm outline-none placeholder:text-white/50"/></div>{replyText&&<button onClick={sendReply} className="w-10 h-10 rounded-full flex items-center justify-center bg-gradient-to-r from-pink-500 to-purple-600"><Send size={16} className="text-white"/></button>}</div></div>;
}
