import {useEffect,useRef,useState} from "react";
import {useLocation,useParams} from "wouter";
import {PhoneOff,Mic,MicOff,Video,VideoOff} from "lucide-react";
import {apiJson} from "@/lib/api";

type Call={id:string;callerId:number;targetUserId:number;status:string};
export default function VideoCall(){
 const [,setLocation]=useLocation();const params=useParams<{userId:string}>();const targetId=Number(params?.userId);const incoming=new URLSearchParams(window.location.search).get("incoming")==="1";const existingCallId=new URLSearchParams(window.location.search).get("callId");const localRef=useRef<HTMLVideoElement>(null);const remoteRef=useRef<HTMLVideoElement>(null);const streamRef=useRef<MediaStream|null>(null);const pcRef=useRef<RTCPeerConnection|null>(null);const pendingIceRef=useRef<RTCIceCandidateInit[]>([]);const callRef=useRef<Call|null>(existingCallId?{id:existingCallId,callerId:targetId,targetUserId:0,status:"connecting"}:null);const cursor=useRef(0);const[state,setState]=useState(incoming?"connecting":"starting");const[muted,setMuted]=useState(false);const[camera,setCamera]=useState(true);const[seconds,setSeconds]=useState(0);const uid=()=>Number(localStorage.getItem("yuniko_user_id")||0);
 const signal=async(type:string,value:unknown)=>{if(callRef.current)await apiJson(`/calls/${callRef.current.id}/signal`,{method:"POST",body:JSON.stringify({type,signal:value})}).catch(()=>{})};
 const flushIce=async()=>{const pc=pcRef.current;if(!pc?.remoteDescription)return;const pending=pendingIceRef.current.splice(0);for(const candidate of pending)await pc.addIceCandidate(candidate).catch(()=>{})};
 useEffect(()=>{let dead=false;(async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({audio:true,video:true});if(dead)return;streamRef.current=stream;if(localRef.current){localRef.current.srcObject=stream;await localRef.current.play().catch(()=>{})}const d=incoming?null:await apiJson<{call:Call}>("/calls/session",{method:"POST",body:JSON.stringify({targetUserId:targetId,kind:"video"})});if(d)callRef.current=d.call;const pc=new RTCPeerConnection({iceServers:[{urls:"stun:stun.l.google.com:19302"}]});pcRef.current=pc;stream.getTracks().forEach(t=>pc.addTrack(t,stream));pc.ontrack=e=>{if(remoteRef.current){remoteRef.current.srcObject=e.streams[0];remoteRef.current.play().catch(()=>{})}};pc.onicecandidate=e=>e.candidate&&signal("candidate",e.candidate);pc.onconnectionstatechange=()=>{if(pc.connectionState==="connected"){setState("connected");if(callRef.current)void apiJson(`/calls/${callRef.current.id}`,{method:"PATCH",body:JSON.stringify({status:"active"})}).catch(()=>{})}else if(["failed","closed"].includes(pc.connectionState))setState("ended")};if(!incoming&&callRef.current?.callerId===uid()){const offer=await pc.createOffer();await pc.setLocalDescription(offer);await signal("offer",offer)}else if(!incoming)setState("waiting");await flushIce()}catch{if(!dead)setState("permission-denied")}})();return()=>{dead=true;pcRef.current?.close();streamRef.current?.getTracks().forEach(t=>t.stop())}},[targetId,incoming]);
 useEffect(()=>{let stop=false;const poll=async()=>{const c=callRef.current;if(!c||stop)return;const d=await apiJson<{signals:Array<{id:number;senderId:number;type:string;payload:string}>>>(`/calls/${c.id}/signals?after=${cursor.current}`).catch(()=>({signals:[]}));for(const s of d.signals){cursor.current=Math.max(cursor.current,s.id);if(s.senderId===uid())continue;const pc=pcRef.current;if(!pc)continue;const value=JSON.parse(s.payload);if(s.type==="offer"){await pc.setRemoteDescription(value);await flushIce();const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await signal("answer",answer)}else if(s.type==="answer"){await pc.setRemoteDescription(value);await flushIce()}else if(s.type==="candidate"){if(pc.remoteDescription)await pc.addIceCandidate(value).catch(()=>{});else pendingIceRef.current.push(value)}}};const id=window.setInterval(poll,600);poll();return()=>{stop=true;window.clearInterval(id)}},[]);
 useEffect(()=>{if(state!=="connected")return;const id=window.setInterval(()=>setSeconds(s=>s+1),1000);return()=>window.clearInterval(id)},[state]);
 const toggleMic=()=>{const t=streamRef.current?.getAudioTracks()[0];if(t){t.enabled=!t.enabled;setMuted(!t.enabled)}};const toggleCam=()=>{const t=streamRef.current?.getVideoTracks()[0];if(t){t.enabled=!t.enabled;setCamera(t.enabled)}};const end=async()=>{if(callRef.current)await apiJson(`/calls/${callRef.current.id}`,{method:"PATCH",body:JSON.stringify({status:"ended"})}).catch(()=>{});pcRef.current?.close();streamRef.current?.getTracks().forEach(t=>t.stop());setLocation("/")};const time=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;
 return <div className="min-h-screen bg-black text-white relative overflow-hidden"><video ref={remoteRef} autoPlay playsInline className="absolute inset-0 w-full h-full object-cover"/><div className="absolute inset-0 flex items-center justify-center text-white/30 pointer-events-none">{state==="permission-denied"?"Camera/microphone permission denied":state==="waiting"?"Waiting for the other user to join…":state==="ended"?"Call ended":state==="starting"?"Starting camera…":""}</div><video ref={localRef} muted playsInline className="absolute right-4 top-12 z-10 w-28 h-40 rounded-2xl object-cover border border-white/20"/><div className="absolute top-5 left-4 z-10"><p className="font-semibold">Video call</p><p className="text-white/50 text-xs">User {targetId||"unknown"} · {state==="connected"?time:"not connected"}</p></div><div className="absolute bottom-8 left-0 right-0 z-20 flex justify-center gap-4"><button onClick={toggleMic} className="w-14 h-14 rounded-full bg-white/10 flex items-center justify-center">{muted?<MicOff/>:<Mic/>}</button><button onClick={toggleCam} className="w-14 h-14 rounded-full bg-white/10 flex items-center justify-center">{camera?<Video/>:<VideoOff/>}</button><button onClick={end} className="w-14 h-14 rounded-full bg-red-500 flex items-center justify-center"><PhoneOff/></button></div></div>;
}
