import {useEffect,useRef,useState} from "react";
import {useLocation,useParams} from "wouter";
import {PhoneOff,Mic,MicOff,Video,VideoOff} from "lucide-react";
import {apiJson} from "@/lib/api";
export default function VideoCall(){const [,setLocation]=useLocation();const params=useParams<{userId:string}>();const targetId=Number(params?.userId);const localRef=useRef<HTMLVideoElement>(null);const streamRef=useRef<MediaStream|null>(null);const [state,setState]=useState("starting");const [muted,setMuted]=useState(false);const [camera,setCamera]=useState(true);const [seconds,setSeconds]=useState(0);
 useEffect(()=>{let active=true;(async()=>{try{const s=await navigator.mediaDevices.getUserMedia({audio:true,video:true});streamRef.current=s;if(localRef.current){localRef.current.srcObject=s;await localRef.current.play().catch(()=>{})}await apiJson(`/calls/session`,{method:"POST",body:JSON.stringify({targetUserId:targetId,kind:"video"})});if(active)setState("waiting");}catch{if(active)setState("permission-denied")}})();return()=>{active=false;streamRef.current?.getTracks().forEach(t=>t.stop())}},[targetId]);
 useEffect(()=>{if(state!=="connected")return;const id=window.setInterval(()=>setSeconds(s=>s+1),1000);return()=>window.clearInterval(id)},[state]);
 const toggleMic=()=>{const t=streamRef.current?.getAudioTracks()[0];if(t){t.enabled=!t.enabled;setMuted(!t.enabled)}};const toggleCam=()=>{const t=streamRef.current?.getVideoTracks()[0];if(t){t.enabled=!t.enabled;setCamera(t.enabled)}};const end=()=>{streamRef.current?.getTracks().forEach(t=>t.stop());setLocation("/")};const time=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;
 return <div className="min-h-screen bg-black text-white relative overflow-hidden"><div className="absolute inset-0 flex items-center justify-center text-white/30 text-center p-8">{state==="permission-denied"?"Camera/microphone permission denied":state==="waiting"?"Waiting for the other user to join…":"Starting camera…"}</div><video ref={localRef} muted playsInline className="absolute right-4 top-12 z-10 w-28 h-40 rounded-2xl object-cover border border-white/20"/><div className="absolute top-5 left-4 z-10"><p className="font-semibold">Video call</p><p className="text-white/50 text-xs">User {targetId||"unknown"} · {state==="connected"?time:"not connected"}</p></div><div className="absolute bottom-8 left-0 right-0 z-20 flex justify-center gap-4"><button onClick={toggleMic} className="w-14 h-14 rounded-full bg-white/10 flex items-center justify-center">{muted?<MicOff/>:<Mic/>}</button><button onClick={toggleCam} className="w-14 h-14 rounded-full bg-white/10 flex items-center justify-center">{camera?<Video/>:<VideoOff/>}</button><button onClick={end} className="w-14 h-14 rounded-full bg-red-500 flex items-center justify-center"><PhoneOff/></button></div></div>;
}
