import {useEffect,useRef,useState} from "react";
import {useLocation,useParams} from "wouter";
import {PhoneOff,Mic,MicOff} from "lucide-react";
import {apiJson} from "@/lib/api";

type Call={id:string;callerId:number;targetUserId:number;status:string};
export default function VoiceCall(){
 const [,setLocation]=useLocation();const params=useParams<{userId:string}>();const targetId=Number(params?.userId);const incoming=new URLSearchParams(window.location.search).get("incoming")==="1";const existingCallId=new URLSearchParams(window.location.search).get("callId");const audioRef=useRef<HTMLAudioElement>(null);const streamRef=useRef<MediaStream|null>(null);const pcRef=useRef<RTCPeerConnection|null>(null);const pendingIceRef=useRef<RTCIceCandidateInit[]>([]);const callRef=useRef<Call|null>(existingCallId?{id:existingCallId,callerId:targetId,targetUserId:0,status:"connecting"}:null);const cursor=useRef(0);const[state,setState]=useState(incoming?"connecting":"starting");const[muted,setMuted]=useState(false);const[seconds,setSeconds]=useState(0);
 const uid=()=>Number(localStorage.getItem("yuniko_user_id")||0);
 const signal=async(type:string,value:unknown)=>{if(callRef.current)await apiJson(`/calls/${callRef.current.id}/signal`,{method:"POST",body:JSON.stringify({type,signal:value})}).catch(()=>{})};
 const flushIce=async()=>{const pc=pcRef.current;if(!pc?.remoteDescription)return;const pending=pendingIceRef.current.splice(0);for(const candidate of pending)await pc.addIceCandidate(candidate).catch(()=>{})};
 useEffect(()=>{let dead=false;(async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});if(dead)return;streamRef.current=stream;const d=incoming?null:await apiJson<{call:Call}>("/calls/session",{method:"POST",body:JSON.stringify({targetUserId:targetId,kind:"voice"})});if(d)callRef.current=d.call;const pc=new RTCPeerConnection({iceServers:[{urls:"stun:stun.l.google.com:19302"}]});pcRef.current=pc;stream.getTracks().forEach(t=>pc.addTrack(t,stream));pc.ontrack=e=>{if(audioRef.current){audioRef.current.srcObject=e.streams[0];audioRef.current.play().catch(()=>{})}};pc.onicecandidate=e=>e.candidate&&signal("candidate",e.candidate);pc.onconnectionstatechange=()=>{if(pc.connectionState==="connected"){setState("connected");if(callRef.current)void apiJson(`/calls/${callRef.current.id}`,{method:"PATCH",body:JSON.stringify({status:"active"})}).catch(()=>{})}else if(["failed","closed"].includes(pc.connectionState))setState("ended")};if(!incoming&&callRef.current?.callerId===uid()){const offer=await pc.createOffer();await pc.setLocalDescription(offer);await signal("offer",offer)}else if(!incoming)setState("waiting");await flushIce()}catch{if(!dead)setState("permission-denied")}})();return()=>{dead=true;pcRef.current?.close();streamRef.current?.getTracks().forEach(t=>t.stop())}},[targetId,incoming]);
 useEffect(()=>{let stop=false;const poll=async()=>{const c=callRef.current;if(!c||stop)return;const d=await apiJson<{signals:Array<{id:number;senderId:number;type:string;payload:string}>>>(`/calls/${c.id}/signals?after=${cursor.current}`).catch(()=>({signals:[]}));for(const s of d.signals){cursor.current=Math.max(cursor.current,s.id);if(s.senderId===uid())continue;const pc=pcRef.current;if(!pc)continue;const value=JSON.parse(s.payload);if(s.type==="offer"){await pc.setRemoteDescription(value);await flushIce();const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await signal("answer",answer)}else if(s.type==="answer"){await pc.setRemoteDescription(value);await flushIce()}else if(s.type==="candidate"){if(pc.remoteDescription)await pc.addIceCandidate(value).catch(()=>{});else pendingIceRef.current.push(value)}}};const id=window.setInterval(poll,600);poll();return()=>{stop=true;window.clearInterval(id)}},[]);
 useEffect(()=>{if(state!=="connected")return;const id=window.setInterval(()=>setSeconds(s=>s+1),1000);return()=>window.clearInterval(id)},[state]);
 const toggle=()=>{const t=streamRef.current?.getAudioTracks()[0];if(t){t.enabled=!t.enabled;setMuted(!t.enabled)}};const end=async()=>{if(callRef.current)await apiJson(`/calls/${callRef.current.id}`,{method:"PATCH",body:JSON.stringify({status:"ended"})}).catch(()=>{});pcRef.current?.close();streamRef.current?.getTracks().forEach(t=>t.stop());setLocation("/")};const time=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;
 return <div className="min-h-screen bg-gradient-to-b from-[#1E1433] to-[#0D0B14] flex flex-col items-center justify-between p-8 text-white"><audio ref={audioRef} autoPlay/><div className="pt-20 text-center"><div className="w-28 h-28 rounded-full mx-auto mb-6 bg-gradient-to-br from-pink-500 to-purple-600 flex items-center justify-center text-4xl">☎</div><h2 className="text-2xl font-bold">Voice call</h2><p className="text-white/50 mt-2">User {targetId||"unknown"}</p><p className="text-pink-400 mt-4">{state==="connected"?time:state==="waiting"?"Waiting for peer…":state==="permission-denied"?"Microphone permission denied":state==="ended"?"Call ended":"Connecting…"}</p></div><div className="flex gap-5 pb-10"><button onClick={toggle} className="w-14 h-14 rounded-full bg-white/10 flex items-center justify-center">{muted?<MicOff/>:<Mic/>}</button><button onClick={end} className="w-14 h-14 rounded-full bg-red-500 flex items-center justify-center"><PhoneOff/></button></div></div>;
}
