import {useEffect,useRef,useState} from "react";
import {useLocation,useParams} from "wouter";
import {PhoneOff,Mic,MicOff} from "lucide-react";
import {apiJson} from "@/lib/api";
export default function VoiceCall(){const [,setLocation]=useLocation();const params=useParams<{userId:string}>();const targetId=Number(params?.userId);const audioRef=useRef<HTMLAudioElement>(null);const streamRef=useRef<MediaStream|null>(null);const [state,setState]=useState("starting");const [muted,setMuted]=useState(false);const [seconds,setSeconds]=useState(0);
 useEffect(()=>{let active=true;(async()=>{try{const s=await navigator.mediaDevices.getUserMedia({audio:true});streamRef.current=s;if(audioRef.current)audioRef.current.srcObject=s;await apiJson(`/calls/session`,{method:"POST",body:JSON.stringify({targetUserId:targetId,kind:"voice"})});if(active)setState("waiting");}catch{if(active)setState("permission-denied")}})();return()=>{active=false;streamRef.current?.getTracks().forEach(t=>t.stop())}},[targetId]);
 useEffect(()=>{if(state!=="connected")return;const id=window.setInterval(()=>setSeconds(s=>s+1),1000);return()=>window.clearInterval(id)},[state]);
 const toggle=()=>{const t=streamRef.current?.getAudioTracks()[0];if(t){t.enabled=!t.enabled;setMuted(!t.enabled)}};const end=()=>{streamRef.current?.getTracks().forEach(t=>t.stop());setLocation("/")};const time=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;
 return <div className="min-h-screen bg-gradient-to-b from-[#1E1433] to-[#0D0B14] flex flex-col items-center justify-between p-8 text-white"><audio ref={audioRef} muted/><div className="pt-20 text-center"><div className="w-28 h-28 rounded-full mx-auto mb-6 bg-gradient-to-br from-pink-500 to-purple-600 flex items-center justify-center text-4xl">☎</div><h2 className="text-2xl font-bold">Voice call</h2><p className="text-white/50 mt-2">User {targetId||"unknown"}</p><p className="text-pink-400 mt-4">{state==="connected"?time:state==="waiting"?"Waiting for peer…":state==="permission-denied"?"Microphone permission denied":"Starting…"}</p></div><div className="flex gap-5 pb-10"><button onClick={toggle} disabled={!streamRef.current} className="w-14 h-14 rounded-full bg-white/10 flex items-center justify-center">{muted?<MicOff/>:<Mic/>}</button><button onClick={end} className="w-14 h-14 rounded-full bg-red-500 flex items-center justify-center"><PhoneOff/></button></div></div>;
}
