import {DurableObject} from "cloudflare:workers";
type A={scope:"inbox"|"room";userId:number};
export class CallSignalRoom extends DurableObject{
constructor(ctx:DurableObjectState,env:unknown){super(ctx,env);this.ctx.setWebSocketAutoResponse(new WebSocketRequestResponsePair("ping","pong"));}
async fetch(request:Request){if(request.headers.get("Upgrade")!=="websocket")return new Response("Expected WebSocket",{status:426});const u=new URL(request.url),scope=u.searchParams.get("scope")==="inbox"?"inbox":"room",userId=Number(u.searchParams.get("userId")||0);if(!Number.isInteger(userId)||userId<=0)return new Response("Invalid user",{status:400});const [client,server]=Object.values(new WebSocketPair());this.ctx.acceptWebSocket(server,[scope]);server.serializeAttachment({scope,userId} satisfies A);return new Response(null,{status:101,webSocket:client});}
async sendInvite(payload:unknown){const m=JSON.stringify(payload);for(const ws of this.ctx.getWebSockets("inbox"))if(ws.readyState===WebSocket.OPEN)ws.send(m);}
async emit(event:string,payload:unknown){const m=JSON.stringify({type:event,...(payload&&typeof payload==="object"?payload:{payload})});for(const ws of this.ctx.getWebSockets("room"))if(ws.readyState===WebSocket.OPEN)ws.send(m);}
async webSocketMessage(ws:WebSocket,message:string|ArrayBuffer){const s=ws.deserializeAttachment() as A|null;if(!s||s.scope!=="room")return;let p:unknown;try{p=JSON.parse(typeof message==="string"?message:new TextDecoder().decode(message));}catch{return}if(!p||typeof p!=="object")return;const d=p as Record<string,unknown>,type=String(d.type||"");if(!["offer","answer","ice","hangup"].includes(type))return;const m=JSON.stringify({type,fromUserId:s.userId,payload:d.payload??null});for(const peer of this.ctx.getWebSockets("room"))if(peer!==ws&&peer.readyState===WebSocket.OPEN)peer.send(m);}
webSocketClose(ws:WebSocket,code:number,reason:string){if(ws.readyState!==WebSocket.CLOSED)ws.close(code,reason);}
}