create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  created_at timestamp without time zone not null default now(),
  updated_at timestamp without time zone not null default now()
);
create index if not exists push_subscriptions_user_id_idx on public.push_subscriptions(user_id);
