create table if not exists public.mobile_push_tokens (
  id bigint generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  token text not null unique,
  platform text not null default 'android',
  created_at timestamp without time zone not null default now(),
  updated_at timestamp without time zone not null default now()
);
create index if not exists mobile_push_tokens_user_id_idx on public.mobile_push_tokens(user_id);
