create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  category text not null,
  message text not null,
  rating integer not null default 0 check (rating between 0 and 5),
  created_at timestamptz not null default now()
);

create index if not exists feedback_user_id_idx on public.feedback(user_id);
create index if not exists feedback_created_at_idx on public.feedback(created_at desc);
